libcopp: coroutine_context_container< TALLOC > Class Template Reference
coroutine_context_container< TALLOC > Class Template Reference
coroutine container contain stack context, stack allocator and runtime fcontext
#include <coroutine_context_container.h>
Public Types
using coroutine_context_type = coroutine_context
using base_type = coroutine_context
using allocator_type = TALLOC
using this_type = coroutine_context_container< allocator_type >
using ptr_type = LIBCOPP_COPP_NAMESPACE_ID::memory::intrusive_ptr< this_type >
using callback_type = coroutine_context::callback_type
using ptr_t = ptr_type
using callback_t = callback_type
using status_type = coroutine_context_base::status_type
using flag_type = coroutine_context_base::flag_type
using status_t = status_type
using flag_t = flag_type
Public Member Functions
~coroutine_context_container ()
const allocator_type & get_allocator () const LIBCOPP_MACRO_NOEXCEPT
get stack allocator
allocator_type & get_allocator () LIBCOPP_MACRO_NOEXCEPT
get stack allocator
size_t use_count () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_COPP_API int start (void *priv_data=nullptr)
start coroutine
LIBCOPP_COPP_API int resume (void *priv_data=nullptr)
resume coroutine
LIBCOPP_COPP_API int yield (void **priv_data=nullptr) LIBCOPP_MACRO_NOEXCEPT
yield coroutine
template<class TAWAITABLE , class TERROR_TRANSFORM , class = nostd::enable_if_t<stackful_inject_awaitable<nostd::remove_cvref_t<TAWAITABLE>>::value>>
LIBCOPP_COPP_API_HEAD_ONLY container_value_type< TAWAITABLE > await_value (TAWAITABLE &&awaitable, TERROR_TRANSFORM &&error_transform) noexcept(std::is_nothrow_copy_constructible< container_value_type< TAWAITABLE > >::value &&noexcept(error_transform(COPP_EC_ARGS_ERROR)))
Waits for the specified awaitable object to finish and retrieves its result.
template<class TAWAITABLE , class = nostd::enable_if_t<stackful_inject_awaitable<nostd::remove_cvref_t<TAWAITABLE>>::value>>
LIBCOPP_COPP_API_HEAD_ONLY container_value_type< TAWAITABLE > await_value (TAWAITABLE &&awaitable) noexcept(std::is_nothrow_copy_constructible< container_value_type< TAWAITABLE > >::value &&noexcept(stackful_channel_error_transform< container_value_type< TAWAITABLE > >()(COPP_EC_ARGS_ERROR)))
Waits for the specified awaitable object to finish and retrieves its result.
LIBCOPP_COPP_API bool set_flags (int flags) LIBCOPP_MACRO_NOEXCEPT
set all flags to true
LIBCOPP_COPP_API bool unset_flags (int flags) LIBCOPP_MACRO_NOEXCEPT
set all flags to false
LIBCOPP_COPP_API bool check_flags (int flags) const LIBCOPP_MACRO_NOEXCEPT
check flags
LIBCOPP_COPP_API int set_runner (callback_type &&runner)
set runner
LIBCOPP_UTIL_FORCEINLINE const std::function< int(void *)> & get_runner () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_UTIL_FORCEINLINE int get_ret_code () const LIBCOPP_MACRO_NOEXCEPT
get runner return code
LIBCOPP_COPP_API bool is_finished () const LIBCOPP_MACRO_NOEXCEPT
get runner return code
LIBCOPP_UTIL_FORCEINLINE void * get_private_buffer () const LIBCOPP_MACRO_NOEXCEPT
get private buffer(raw pointer)
LIBCOPP_UTIL_FORCEINLINE size_t get_private_buffer_size () const LIBCOPP_MACRO_NOEXCEPT
get private buffer size
Static Public Member Functions
static ptr_type create (callback_type &&runner, allocator_type &alloc, size_t stack_sz=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
create and init coroutine with specify runner and specify stack size
template<class TRunner >
static ptr_type create (TRunner *runner, allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static ptr_type create (int(*fn)(void *), allocator_type &alloc, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static ptr_type create (callback_type &&runner, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
template<class TRunner >
static ptr_type create (TRunner *runner, size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static ptr_type create (int(*fn)(void *), size_t stack_size=0, size_t private_buffer_size=0, size_t coroutine_size=0) LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API int create (coroutine_context *p, callback_type &&runner, const stack_context &callee_stack, size_t coroutine_size, size_t private_buffer_size) LIBCOPP_MACRO_NOEXCEPT
create coroutine context at stack context callee_
template<typename TRunner >
static LIBCOPP_COPP_API_HEAD_ONLY int create (coroutine_context *p, TRunner *runner, const stack_context &callee_stack, size_t coroutine_size, size_t private_buffer_size) LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_UTIL_FORCEINLINE size_t align_private_data_size (size_t sz)
static size_t align_address_size (size_t sz)
static size_t align_stack_size (size_t sz)
static LIBCOPP_COPP_API coroutine_context_base * get_this_coroutine_base () LIBCOPP_MACRO_NOEXCEPT
get current coroutine
static LIBCOPP_COPP_API void set_this_coroutine_base (coroutine_context_base *ctx) LIBCOPP_MACRO_NOEXCEPT
set current coroutine
Protected Member Functions
LIBCOPP_UTIL_FORCEINLINE void run_and_recv_retcode (void *priv_data)
coroutine entrance function
Protected Attributes
fcontext::fcontext_t caller_
fcontext::fcontext_t callee_
stack_context callee_stack_
Private Member Functions
coroutine_context_container (const allocator_type &alloc) LIBCOPP_MACRO_NOEXCEPT
coroutine_context_container (allocator_type &&alloc) LIBCOPP_MACRO_NOEXCEPT
coroutine_context_container (const coroutine_context_container &)=delete
Private Attributes
allocator_type alloc_
LIBCOPP_COPP_NAMESPACE_ID::util::lock::atomic_int_type< LIBCOPP_COPP_NAMESPACE_ID::util::lock::unsafe_int_type< size_t > > ref_count_
int flags_
void * priv_data_
size_t private_buffer_size_
callback_type runner_
int runner_ret_code_
LIBCOPP_COPP_NAMESPACE_ID::util::lock::atomic_int_type< LIBCOPP_COPP_NAMESPACE_ID::util::lock::unsafe_int_type< int > > status_
Friends
void intrusive_ptr_add_ref (this_type *p)
void intrusive_ptr_release (this_type *p)
Detailed Description
template<typename TALLOC>
class coroutine_context_container< TALLOC >
coroutine container contain stack context, stack allocator and runtime fcontext
Definition at line 26 of file coroutine_context_container.h.
Member Typedef Documentation
allocator_type
template<typename TALLOC > using coroutine_context_container< TALLOC >::allocator_type = TALLOC
Definition at line 30 of file coroutine_context_container.h.
base_type
template<typename TALLOC > using coroutine_context_container< TALLOC >::base_type = coroutine_context
Definition at line 29 of file coroutine_context_container.h.
callback_t
template<typename TALLOC > using coroutine_context_container< TALLOC >::callback_t = callback_type
Definition at line 37 of file coroutine_context_container.h.
callback_type
template<typename TALLOC > using coroutine_context_container< TALLOC >::callback_type = coroutine_context::callback_type
Definition at line 33 of file coroutine_context_container.h.
coroutine_context_type
template<typename TALLOC > using coroutine_context_container< TALLOC >::coroutine_context_type = coroutine_context
Definition at line 28 of file coroutine_context_container.h.
flag_t
using coroutine_context::flag_t = flag_type inherited
Definition at line 39 of file coroutine_context.h.
flag_type
using coroutine_context::flag_type = coroutine_context_base::flag_type inherited
Definition at line 33 of file coroutine_context.h.
ptr_t
template<typename TALLOC > using coroutine_context_container< TALLOC >::ptr_t = ptr_type
Definition at line 36 of file coroutine_context_container.h.
ptr_type
template<typename TALLOC > using coroutine_context_container< TALLOC >::ptr_type = LIBCOPP_COPP_NAMESPACE_ID::memory::intrusive_ptr<this_type>
Definition at line 32 of file coroutine_context_container.h.
status_t
using coroutine_context::status_t = status_type inherited
Definition at line 38 of file coroutine_context.h.
status_type
using coroutine_context::status_type = coroutine_context_base::status_type inherited
Definition at line 32 of file coroutine_context.h.
this_type
template<typename TALLOC > using coroutine_context_container< TALLOC >::this_type = coroutine_context_container<allocator_type>
Definition at line 31 of file coroutine_context_container.h.
Constructor & Destructor Documentation
coroutine_context_container() [1/3]
template<typename TALLOC > coroutine_context_container< TALLOC >::coroutine_context_container (const allocator_type & alloc) inline private
Definition at line 42 of file coroutine_context_container.h.
coroutine_context_container() [2/3]
template<typename TALLOC > coroutine_context_container< TALLOC >::coroutine_context_container (allocator_type && alloc) inline private
Definition at line 44 of file coroutine_context_container.h.
~coroutine_context_container()
template<typename TALLOC > coroutine_context_container< TALLOC >::~coroutine_context_container () inline
Definition at line 48 of file coroutine_context_container.h.
coroutine_context_container() [3/3]
template<typename TALLOC > coroutine_context_container< TALLOC >::coroutine_context_container (const coroutine_context_container< TALLOC > &) private delete
Member Function Documentation
align_address_size()
static size_t coroutine_context_base::align_address_size (size_t sz) inline static inherited
Definition at line 223 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_BASE_ALIGN_UNIT_SIZE.
Referenced by coroutine_context_container< TALLOC >::create().
align_private_data_size()
static LIBCOPP_UTIL_FORCEINLINE size_t coroutine_context_base::align_private_data_size (size_t sz) inline static inherited
Definition at line 207 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_BASE_ALIGN_UNIT_SIZE.
Referenced by coroutine_context_container< TALLOC >::create().
align_stack_size()
static size_t coroutine_context_base::align_stack_size (size_t sz) inline static inherited
Definition at line 231 of file coroutine_context_base.h.
References COROUTINE_CONTEXT_STACK_ALIGN_UNIT_SIZE.
await_value() [1/2]
template<class TAWAITABLE , class = nostd::enable_if_t<stackful_inject_awaitable<nostd::remove_cvref_t<TAWAITABLE>>::value>> LIBCOPP_COPP_API_HEAD_ONLY container_value_type< TAWAITABLE > coroutine_context::await_value (TAWAITABLE && awaitable) inline noexcept inherited
Waits for the specified awaitable object to finish and retrieves its result.
Parameters
awaitable The awaitable object to be consumed.
Returns
The result of the awaitable object, of type TAWAITABLE::value_type. If any error happens it will call value_type's constructor and pass error code.
Definition at line 172 of file coroutine_context.h.
await_value() [2/2]
template<class TAWAITABLE , class TERROR_TRANSFORM , class = nostd::enable_if_t<stackful_inject_awaitable<nostd::remove_cvref_t<TAWAITABLE>>::value>> LIBCOPP_COPP_API_HEAD_ONLY container_value_type< TAWAITABLE > coroutine_context::await_value (TAWAITABLE && awaitable, TERROR_TRANSFORM && error_transform) inline noexcept inherited
Waits for the specified awaitable object to finish and retrieves its result.
Parameters
awaitable The awaitable object to be consumed.
error_transform A callable object used to transform error code to return type if any occur.
Returns
The result of the awaitable object, of type TAWAITABLE::value_type.
Definition at line 156 of file coroutine_context.h.
check_flags()
LIBCOPP_COPP_API bool coroutine_context_base::check_flags (int flags) const inherited
check flags
Parameters
flags flags to be checked
Returns
true if flags any flags is true
Definition at line 98 of file coroutine_context.cpp.
Referenced by this_coroutine::get_coroutine(), and coroutine_context::start().
create() [1/8]
template<typename TALLOC > static ptr_type coroutine_context_container< TALLOC >::create (callback_type && runner, allocator_type & alloc, size_t stack_sz = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
create and init coroutine with specify runner and specify stack size
Parameters
runner runner
stack_sz stack size
private_buffer_size private buffer size
coroutine_size extend buffer before coroutine
Returns
COPP_EC_SUCCESS or error code
Definition at line 71 of file coroutine_context_container.h.
References coroutine_context_base::align_address_size(), coroutine_context_base::align_private_data_size(), coroutine_context::create(), stack_traits::default_size(), stack_context::reset(), and stack_context::sp.
Referenced by coroutine_context_container< TALLOC >::create(), coroutine_context_container< TALLOC >::create(), coroutine_context_container< TALLOC >::create(), coroutine_context_container< TALLOC >::create(), coroutine_context_container< TALLOC >::create(), main(), and main().
create() [2/8]
template<typename TALLOC > static ptr_type coroutine_context_container< TALLOC >::create (callback_type && runner, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 138 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::create().
create() [3/8]
LIBCOPP_COPP_API int coroutine_context::create (coroutine_context * p, callback_type && runner, const stack_context & callee_stack, size_t coroutine_size, size_t private_buffer_size) static inherited
create coroutine context at stack context callee_
Parameters
runner runner
callee_stack stack context
coroutine_size size of coroutine object
private_buffer_size size of private buffer
Returns
COPP_EC_SUCCESS or error code
Definition at line 284 of file coroutine_context.cpp.
References COPP_EC_ARGS_ERROR, COPP_EC_FCONTEXT_MAKE_FAILED, COPP_EC_SUCCESS, fcontext::copp_make_fcontext_v2(), and libcopp_internal_api_set::coroutine_context_callback().
Referenced by coroutine_context_container< TALLOC >::create(), and coroutine_context::create().
create() [4/8]
template<typename TRunner > static LIBCOPP_COPP_API_HEAD_ONLY int coroutine_context::create (coroutine_context * p, TRunner * runner, const stack_context & callee_stack, size_t coroutine_size, size_t private_buffer_size) inline static inherited
Definition at line 94 of file coroutine_context.h.
References coroutine_context::create().
create() [5/8]
template<typename TALLOC > static ptr_type coroutine_context_container< TALLOC >::create (int(*)(void *) fn, allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 129 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::create().
create() [6/8]
template<typename TALLOC > static ptr_type coroutine_context_container< TALLOC >::create (int(*)(void *) fn, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 151 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::create().
create() [7/8]
template<typename TALLOC > template<class TRunner > static ptr_type coroutine_context_container< TALLOC >::create (TRunner * runner, allocator_type & alloc, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 119 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::create().
create() [8/8]
template<typename TALLOC > template<class TRunner > static ptr_type coroutine_context_container< TALLOC >::create (TRunner * runner, size_t stack_size = 0, size_t private_buffer_size = 0, size_t coroutine_size = 0) inline static
Definition at line 145 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::create().
get_allocator() [1/2]
template<typename TALLOC > const allocator_type & coroutine_context_container< TALLOC >::get_allocator () const inline
get stack allocator
Returns
stack allocator
Definition at line 54 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::alloc_.
get_allocator() [2/2]
template<typename TALLOC > allocator_type & coroutine_context_container< TALLOC >::get_allocator () inline
get stack allocator
Returns
stack allocator
Definition at line 60 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::alloc_.
get_private_buffer()
LIBCOPP_UTIL_FORCEINLINE void * coroutine_context_base::get_private_buffer () const inline inherited
get private buffer(raw pointer)
Definition at line 197 of file coroutine_context_base.h.
References coroutine_context_base::priv_data_.
get_private_buffer_size()
LIBCOPP_UTIL_FORCEINLINE size_t coroutine_context_base::get_private_buffer_size () const inline inherited
get private buffer size
Definition at line 202 of file coroutine_context_base.h.
References coroutine_context_base::private_buffer_size_.
get_ret_code()
LIBCOPP_UTIL_FORCEINLINE int coroutine_context_base::get_ret_code () const inline inherited
get runner return code
Returns
Definition at line 186 of file coroutine_context_base.h.
References coroutine_context_base::runner_ret_code_.
get_runner()
LIBCOPP_UTIL_FORCEINLINE const std::function< int(void *)> & coroutine_context_base::get_runner () const inline inherited
get runner of this coroutine context (const)
Returns
nullptr of pointer of runner
Definition at line 178 of file coroutine_context_base.h.
References coroutine_context_base::runner_.
get_this_coroutine_base()
LIBCOPP_COPP_API coroutine_context_base * coroutine_context_base::get_this_coroutine_base () static inherited
get current coroutine
See also
detail::coroutine_context_base
Returns
pointer of current coroutine, if not in coroutine, return nullptr
Definition at line 123 of file coroutine_context.cpp.
References detail::get_this_coroutine_context().
is_finished()
LIBCOPP_COPP_API bool coroutine_context_base::is_finished () const inherited
get runner return code
Returns
true if coroutine has run and finished
Definition at line 118 of file coroutine_context.cpp.
References coroutine_context_base::status_type::EN_CRS_FINISHED, and coroutine_context_base::status_.
resume()
LIBCOPP_COPP_API int coroutine_context::resume (void * priv_data = nullptr) inherited
resume coroutine
Parameters
priv_data private data, will be passed to runner operator() or return to yield
Exceptions
if exception is enabled, it will throw all unhandled exception after resumed
Returns
COPP_EC_SUCCESS or error code
Definition at line 416 of file coroutine_context.cpp.
References coroutine_context::start().
run_and_recv_retcode()
LIBCOPP_UTIL_FORCEINLINE void coroutine_context_base::run_and_recv_retcode (void * priv_data) inline protected inherited
coroutine entrance function
Definition at line 160 of file coroutine_context_base.h.
References coroutine_context_base::runner_, and coroutine_context_base::runner_ret_code_.
Referenced by libcopp_internal_api_set::coroutine_context_callback().
set_flags()
LIBCOPP_COPP_API bool coroutine_context_base::set_flags (int flags) inherited
set all flags to true
Parameters
flags (flags & EN_CFT_MASK) must be 0
Returns
true if flags is available, or return false
Definition at line 80 of file coroutine_context.cpp.
set_runner()
LIBCOPP_COPP_API int coroutine_context_base::set_runner (callback_type && runner) inherited
set runner
Parameters
runner
Returns
COPP_EC_SUCCESS or error code
Definition at line 102 of file coroutine_context.cpp.
References COPP_EC_ALREADY_INITED, COPP_EC_ARGS_ERROR, COPP_EC_SUCCESS, coroutine_context_base::status_type::EN_CRS_INVALID, coroutine_context_base::status_type::EN_CRS_READY, coroutine_context_base::runner_, and coroutine_context_base::status_.
set_this_coroutine_base()
LIBCOPP_COPP_API void coroutine_context_base::set_this_coroutine_base (coroutine_context_base * ctx) static inherited
set current coroutine
See also
detail::coroutine_context_base
Parameters
ctx pointer of current coroutine, if not in coroutine, set nullptr
Definition at line 127 of file coroutine_context.cpp.
References detail::set_this_coroutine_context().
start()
LIBCOPP_COPP_API int coroutine_context::start (void * priv_data = nullptr) inherited
start coroutine
Parameters
priv_data private data, will be passed to runner operator() or return to yield
Exceptions
if exception is enabled, it will throw all unhandled exception after resumed
Returns
COPP_EC_SUCCESS or error code
Definition at line 348 of file coroutine_context.cpp.
References coroutine_context::callee_, coroutine_context::callee_stack_, coroutine_context_base::check_flags(), COPP_EC_IS_RUNNING, COPP_EC_NOT_INITED, COPP_EC_NOT_READY, COPP_EC_SUCCESS, coroutine_context_base::flag_type::EN_CFT_FINISHED, coroutine_context_base::flag_type::EN_CFT_IS_FIBER, coroutine_context_base::status_type::EN_CRS_EXITED, coroutine_context_base::status_type::EN_CRS_READY, coroutine_context_base::status_type::EN_CRS_RUNNING, coroutine_context::jump_src_data_t::from_co, detail::get_this_coroutine_context(), jump_to(), LIBCOPP_UTIL_UNLIKELY_CONDITION, coroutine_context::jump_src_data_t::priv_data, coroutine_context::status_, std::swap(), and coroutine_context::jump_src_data_t::to_co.
Referenced by coroutine_context::resume().
unset_flags()
LIBCOPP_COPP_API bool coroutine_context_base::unset_flags (int flags) inherited
set all flags to false
Parameters
flags (flags & EN_CFT_MASK) must be 0
Returns
true if flags is available, or return false
Definition at line 89 of file coroutine_context.cpp.
use_count()
template<typename TALLOC > size_t coroutine_context_container< TALLOC >::use_count () const inline
Definition at line 156 of file coroutine_context_container.h.
References coroutine_context_container< TALLOC >::ref_count_.
yield()
LIBCOPP_COPP_API int coroutine_context::yield (void ** priv_data = nullptr) inherited
yield coroutine
Parameters
priv_data private data, if not nullptr, will get the value from start(priv_data) or resume(priv_data)
Returns
COPP_EC_SUCCESS or error code
Definition at line 423 of file coroutine_context.cpp.
References COPP_EC_ALREADY_EXIST, COPP_EC_NOT_INITED, COPP_EC_NOT_RUNNING, COPP_EC_SUCCESS, COPP_EC_UNKNOWN, coroutine_context::jump_src_data_t::from_co, jump_to(), coroutine_context::jump_src_data_t::priv_data, and coroutine_context::jump_src_data_t::to_co.
Referenced by libcopp_internal_api_set::coroutine_context_callback(), and this_coroutine::yield().
Friends And Related Symbol Documentation
intrusive_ptr_add_ref
template<typename TALLOC > void intrusive_ptr_add_ref (this_type * p) friend
Definition at line 162 of file coroutine_context_container.h.
intrusive_ptr_release
template<typename TALLOC > void intrusive_ptr_release (this_type * p) friend
Definition at line 170 of file coroutine_context_container.h.
Field Documentation
alloc_
template<typename TALLOC > allocator_type coroutine_context_container< TALLOC >::alloc_ private
Definition at line 189 of file coroutine_context_container.h.
Referenced by coroutine_context_container< TALLOC >::get_allocator(), and coroutine_context_container< TALLOC >::get_allocator().
callee_
fcontext::fcontext_t coroutine_context::callee_ protected inherited
caller runtime context
Definition at line 62 of file coroutine_context.h.
Referenced by libcopp_internal_api_set::coroutine_context_callback(), libcopp_internal_api_set::set_callee(), and coroutine_context::start().
callee_stack_
stack_context coroutine_context::callee_stack_ protected inherited
callee runtime context
Definition at line 64 of file coroutine_context.h.
Referenced by coroutine_context::start().
caller_
fcontext::fcontext_t coroutine_context::caller_ protected inherited
Definition at line 61 of file coroutine_context.h.
Referenced by libcopp_internal_api_set::coroutine_context_callback(), and libcopp_internal_api_set::set_caller().
flags_
int coroutine_context_base::flags_ private inherited
coroutine return code
Definition at line 105 of file coroutine_context_base.h.
Referenced by libcopp_internal_api_set::coroutine_context_callback().
priv_data_
void* coroutine_context_base::priv_data_ private inherited
coroutine runner
Definition at line 107 of file coroutine_context_base.h.
private_buffer_size_
size_t coroutine_context_base::private_buffer_size_ private inherited
Definition at line 108 of file coroutine_context_base.h.
ref_count_
template<typename TALLOC > LIBCOPP_COPP_NAMESPACE_ID::util::lock::atomic_int_type< LIBCOPP_COPP_NAMESPACE_ID::util::lock::unsafe_int_type<size_t> > coroutine_context_container< TALLOC >::ref_count_ private
stack allocator
Definition at line 195 of file coroutine_context_container.h.
Referenced by coroutine_context_container< TALLOC >::use_count().
runner_
callback_type coroutine_context_base::runner_ private inherited
flags
Definition at line 106 of file coroutine_context_base.h.
runner_ret_code_
int coroutine_context_base::runner_ret_code_ private inherited
Definition at line 104 of file coroutine_context_base.h.
status_
LIBCOPP_COPP_NAMESPACE_ID::util::lock::atomic_int_type<LIBCOPP_COPP_NAMESPACE_ID::util::lock::unsafe_int_type<int> > coroutine_context_base::status_ private inherited
Definition at line 114 of file coroutine_context_base.h.
Referenced by coroutine_context::start().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/coroutine/coroutine_context_container.h