libcopp: memory::__weak_rc_counter< T > Class Template Reference
memory::__weak_rc_counter< T > Class Template Reference
#include <rc_ptr.h>
Public Member Functions
constexpr __weak_rc_counter () noexcept
template<class Y >
__weak_rc_counter (const __strong_rc_counter< Y > &other) noexcept
~__weak_rc_counter ()
__weak_rc_counter (const __weak_rc_counter &r) noexcept
__weak_rc_counter (__weak_rc_counter &&r) noexcept
template<class Y >
__weak_rc_counter (const __weak_rc_counter< Y > &r) noexcept
template<class Y >
__weak_rc_counter (__weak_rc_counter< Y > &&r) noexcept
__weak_rc_counter & operator= (const __weak_rc_counter &r) noexcept
__weak_rc_counter & operator= (__weak_rc_counter &&r) noexcept
void swap (__weak_rc_counter &r) noexcept
template<class Y >
void swap (__weak_rc_counter< Y > &r) noexcept
std::size_t use_count () const noexcept
__rc_ptr_counted_data_base * ref_counter () const noexcept
Private Attributes
__rc_ptr_counted_data_base * pi_
Friends
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY __weak_rc_counter
Detailed Description
template<class T>
class memory::__weak_rc_counter< T >
Definition at line 565 of file rc_ptr.h.
Constructor & Destructor Documentation
__weak_rc_counter() [1/6]
template<class T > constexpr memory::__weak_rc_counter< T >::__weak_rc_counter () inline constexpr noexcept
Definition at line 567 of file rc_ptr.h.
__weak_rc_counter() [2/6]
template<class T > template<class Y > memory::__weak_rc_counter< T >::__weak_rc_counter (const __strong_rc_counter< Y > & other) inline explicit noexcept
Definition at line 570 of file rc_ptr.h.
~__weak_rc_counter()
template<class T > memory::__weak_rc_counter< T >::~__weak_rc_counter () inline
Definition at line 576 of file rc_ptr.h.
__weak_rc_counter() [3/6]
template<class T > memory::__weak_rc_counter< T >::__weak_rc_counter (const __weak_rc_counter< T > & r) inline noexcept
Definition at line 582 of file rc_ptr.h.
__weak_rc_counter() [4/6]
template<class T > memory::__weak_rc_counter< T >::__weak_rc_counter (__weak_rc_counter< T > && r) inline noexcept
Definition at line 588 of file rc_ptr.h.
__weak_rc_counter() [5/6]
template<class T > template<class Y > memory::__weak_rc_counter< T >::__weak_rc_counter (const __weak_rc_counter< Y > & r) inline noexcept
Definition at line 591 of file rc_ptr.h.
__weak_rc_counter() [6/6]
template<class T > template<class Y > memory::__weak_rc_counter< T >::__weak_rc_counter (__weak_rc_counter< Y > && r) inline noexcept
Definition at line 598 of file rc_ptr.h.
Member Function Documentation
operator=() [1/2]
template<class T > __weak_rc_counter & memory::__weak_rc_counter< T >::operator= (__weak_rc_counter< T > && r) inline noexcept
Definition at line 617 of file rc_ptr.h.
References memory::__rc_ptr_counted_data_base::weak_release().
operator=() [2/2]
template<class T > __weak_rc_counter & memory::__weak_rc_counter< T >::operator= (const __weak_rc_counter< T > & r) inline noexcept
Definition at line 602 of file rc_ptr.h.
References memory::__rc_ptr_counted_data_base::weak_add_ref(), and memory::__rc_ptr_counted_data_base::weak_release().
ref_counter()
template<class T > __rc_ptr_counted_data_base * memory::__weak_rc_counter< T >::ref_counter () const inline noexcept
Definition at line 645 of file rc_ptr.h.
swap() [1/2]
template<class T > void memory::__weak_rc_counter< T >::swap (__weak_rc_counter< T > & r) inline noexcept
Definition at line 630 of file rc_ptr.h.
Referenced by memory::weak_rc_ptr< T >::operator=().
swap() [2/2]
template<class T > template<class Y > void memory::__weak_rc_counter< T >::swap (__weak_rc_counter< Y > & r) inline noexcept
Definition at line 637 of file rc_ptr.h.
use_count()
template<class T > std::size_t memory::__weak_rc_counter< T >::use_count () const inline noexcept
Definition at line 643 of file rc_ptr.h.
Friends And Related Symbol Documentation
__weak_rc_counter
template<class T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY __weak_rc_counter friend
Definition at line 649 of file rc_ptr.h.
Field Documentation
pi_
template<class T > __rc_ptr_counted_data_base* memory::__weak_rc_counter< T >::pi_ private
Definition at line 651 of file rc_ptr.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h