libcopp: strong_rc::n_spt_another_sp::another_ptr< T > Class Template Reference
strong_rc::n_spt_another_sp::another_ptr< T > Class Template Reference
Public Member Functions
another_ptr (T *p=0)
void reset ()
T * get () const
Private Types
typedef copp::memory::strong_rc_ptr< T > base_type
Detailed Description
template<class T>
class strong_rc::n_spt_another_sp::another_ptr< T >
Definition at line 2359 of file rc_ptr_test.cpp.
Member Typedef Documentation
base_type
template<class T > typedef copp::memory::strong_rc_ptr<T> strong_rc::n_spt_another_sp::another_ptr< T >::base_type private
Definition at line 2361 of file rc_ptr_test.cpp.
Constructor & Destructor Documentation
another_ptr()
template<class T > strong_rc::n_spt_another_sp::another_ptr< T >::another_ptr (T * p = 0) inline explicit
Definition at line 2364 of file rc_ptr_test.cpp.
Member Function Documentation
get()
template<class T > T * strong_rc::n_spt_another_sp::another_ptr< T >::get () const inline
Definition at line 2368 of file rc_ptr_test.cpp.
Referenced by strong_rc::n_spt_another_sp::test().
reset()
template<class T > void strong_rc::n_spt_another_sp::another_ptr< T >::reset () inline
Definition at line 2366 of file rc_ptr_test.cpp.
Referenced by strong_rc::n_spt_another_sp::remove_event_handler(), and strong_rc::n_spt_another_sp::test().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/test/case/rc_ptr_test.cpp