libcopp: memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc > Class Template Reference
memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc > Class Template Reference final
Template class definition for reference-counted with allocator.(inplacement)
#include <rc_ptr.h>
Public Member Functions
template<class AllocInput , class... Args>
__rc_ptr_counted_data_inplace_alloc (AllocInput &&a, Args &&... args)
void dispose () noexcept override
void destroy () noexcept override
T * value_ptr () noexcept
Alloc * alloc_ptr () noexcept
LIBCOPP_UTIL_FORCEINLINE void add_ref ()
LIBCOPP_UTIL_FORCEINLINE bool add_ref_nothrow () noexcept
LIBCOPP_UTIL_FORCEINLINE void release () noexcept
LIBCOPP_UTIL_FORCEINLINE void weak_add_ref () noexcept
LIBCOPP_UTIL_FORCEINLINE void weak_release () noexcept
LIBCOPP_UTIL_FORCEINLINE std::size_t use_count () const noexcept
Static Public Member Functions
static LIBCOPP_COPP_API void throw_bad_weak_ptr ()
Private Member Functions
void * value_addr ()
void * alloc_addr ()
Private Attributes
nostd::aligned_storage_t< sizeof(T), alignof(T)> storage_
nostd::aligned_storage_t< sizeof(Alloc), alignof(Alloc)> alloc_
std::size_t use_count_
std::size_t weak_count_
Detailed Description
template<class T, class Alloc>
class memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >
Template class definition for reference-counted with allocator.(inplacement)
Note
Construct object and counter inplace with custom allocator. This will reduce memory fragmentation and slightly improve performance.
We use allocator rebind to allocate all data with custom allocator.
Definition at line 178 of file rc_ptr.h.
Constructor & Destructor Documentation
__rc_ptr_counted_data_inplace_alloc()
template<class T , class Alloc > template<class AllocInput , class... Args> memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::__rc_ptr_counted_data_inplace_alloc (AllocInput && a, Args &&... args) inline explicit
Definition at line 181 of file rc_ptr.h.
Member Function Documentation
add_ref()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::add_ref () inline inherited
Definition at line 54 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::operator=().
add_ref_nothrow()
LIBCOPP_UTIL_FORCEINLINE bool memory::__rc_ptr_counted_data_base::add_ref_nothrow () inline noexcept inherited
Definition at line 61 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::__strong_rc_counter().
alloc_addr()
template<class T , class Alloc > void * memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::alloc_addr () inline private
Definition at line 248 of file rc_ptr.h.
alloc_ptr()
template<class T , class Alloc > Alloc * memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::alloc_ptr () inline noexcept
Definition at line 244 of file rc_ptr.h.
destroy()
template<class T , class Alloc > void memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::destroy () inline override virtual noexcept
Implements memory::__rc_ptr_counted_data_base.
Definition at line 208 of file rc_ptr.h.
References LIBCOPP_UTIL_ATTRIBUTE_UNINITIALIZED.
dispose()
template<class T , class Alloc > void memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::dispose () inline override virtual noexcept
Implements memory::__rc_ptr_counted_data_base.
Definition at line 203 of file rc_ptr.h.
release()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::release () inline noexcept inherited
Definition at line 71 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::operator=(), and memory::__strong_rc_counter< T >::operator=().
throw_bad_weak_ptr()
LIBCOPP_COPP_API void memory::__rc_ptr_counted_data_base::throw_bad_weak_ptr () static inherited
Definition at line 13 of file rc_ptr.cpp.
Referenced by memory::__strong_rc_counter< T >::__strong_rc_counter(), memory::enable_shared_rc_from_this< T >::shared_from_this(), and memory::enable_shared_rc_from_this< T >::shared_from_this().
use_count()
LIBCOPP_UTIL_FORCEINLINE std::size_t memory::__rc_ptr_counted_data_base::use_count () const inline noexcept inherited
Definition at line 90 of file rc_ptr.h.
value_addr()
template<class T , class Alloc > void * memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::value_addr () inline private
Definition at line 247 of file rc_ptr.h.
value_ptr()
template<class T , class Alloc > T * memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::value_ptr () inline noexcept
Definition at line 243 of file rc_ptr.h.
weak_add_ref()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::weak_add_ref () inline noexcept inherited
Definition at line 81 of file rc_ptr.h.
Referenced by memory::__weak_rc_counter< T >::operator=().
weak_release()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::weak_release () inline noexcept inherited
Definition at line 84 of file rc_ptr.h.
Referenced by memory::__weak_rc_counter< T >::operator=(), and memory::__weak_rc_counter< T >::operator=().
Field Documentation
alloc_
template<class T , class Alloc > nostd::aligned_storage_t<sizeof(Alloc), alignof(Alloc)> memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::alloc_ private
Definition at line 251 of file rc_ptr.h.
storage_
template<class T , class Alloc > nostd::aligned_storage_t<sizeof(T), alignof(T)> memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >::storage_ private
Definition at line 250 of file rc_ptr.h.
use_count_
std::size_t memory::__rc_ptr_counted_data_base::use_count_ private inherited
Definition at line 97 of file rc_ptr.h.
weak_count_
std::size_t memory::__rc_ptr_counted_data_base::weak_count_ private inherited
Definition at line 98 of file rc_ptr.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h