libcopp: fcontext Namespace Reference
fcontext Namespace Reference
Data Structures
struct stack_t
struct fp_t
struct fcontext_t
struct transfer_t
Typedefs
using fcontext_t = void *
Functions
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL copp_jump_fcontext_v2 (fcontext_t const to, void *vp)
COPP_BOOST_CONTEXT_DECL fcontext_t COPP_BOOST_CONTEXT_CALLDECL copp_make_fcontext_v2 (void *sp, std::size_t size, void(*fn)(transfer_t))
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL copp_ontop_fcontext_v2 (fcontext_t const to, void *vp, transfer_t(*fn)(transfer_t))
Typedef Documentation
fcontext_t
using fcontext::fcontext_t = typedef void*
Definition at line 27 of file fcontext.hpp.
Function Documentation
copp_jump_fcontext_v2()
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL fcontext::copp_jump_fcontext_v2 (fcontext_t const to, void * vp)
Referenced by CASE_TEST(), jump_to(), test_core_fcontext_func_a(), and test_core_fcontext_func_b().
copp_make_fcontext_v2()
COPP_BOOST_CONTEXT_DECL fcontext_t COPP_BOOST_CONTEXT_CALLDECL fcontext::copp_make_fcontext_v2 (void * sp, std::size_t size, void(*)(transfer_t) fn)
Referenced by CASE_TEST(), and coroutine_context::create().
copp_ontop_fcontext_v2()
COPP_BOOST_CONTEXT_DECL transfer_t COPP_BOOST_CONTEXT_CALLDECL fcontext::copp_ontop_fcontext_v2 (fcontext_t const to, void * vp, transfer_t(*)(transfer_t) fn)