libcopp: memory::enable_shared_rc_from_this< T > Class Template Reference
memory::enable_shared_rc_from_this< T > Class Template Reference
#include <rc_ptr.h>
Public Member Functions
strong_rc_ptr< T > shared_from_this ()
strong_rc_ptr< const T > shared_from_this () const
weak_rc_ptr< T > weak_from_this ()
weak_rc_ptr< const T > weak_from_this () const
template<class Y >
void __internal_weak_assign (T *__p, const __strong_rc_counter< Y > &__n) const noexcept
Protected Member Functions
enable_shared_rc_from_this ()=default
enable_shared_rc_from_this (const enable_shared_rc_from_this &)=default
enable_shared_rc_from_this & operator= (const enable_shared_rc_from_this &)=default
~enable_shared_rc_from_this ()=default
Private Attributes
weak_rc_ptr< T > weak_this_
Friends
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY strong_rc_ptr
Detailed Description
template<class T>
class memory::enable_shared_rc_from_this< T >
Definition at line 1247 of file rc_ptr.h.
Constructor & Destructor Documentation
enable_shared_rc_from_this() [1/2]
template<class T > memory::enable_shared_rc_from_this< T >::enable_shared_rc_from_this () protected default
enable_shared_rc_from_this() [2/2]
template<class T > memory::enable_shared_rc_from_this< T >::enable_shared_rc_from_this (const enable_shared_rc_from_this< T > &) protected default
~enable_shared_rc_from_this()
template<class T > memory::enable_shared_rc_from_this< T >::~enable_shared_rc_from_this () protected default
Member Function Documentation
__internal_weak_assign()
template<class T > template<class Y > void memory::enable_shared_rc_from_this< T >::__internal_weak_assign (T * __p, const __strong_rc_counter< Y > & __n) const inline noexcept
Definition at line 1287 of file rc_ptr.h.
References memory::enable_shared_rc_from_this< T >::weak_this_.
Referenced by memory::__enable_shared_from_this_with().
operator=()
template<class T > enable_shared_rc_from_this & memory::enable_shared_rc_from_this< T >::operator= (const enable_shared_rc_from_this< T > &) protected default
shared_from_this() [1/2]
template<class T > strong_rc_ptr< T > memory::enable_shared_rc_from_this< T >::shared_from_this () inline
Definition at line 1249 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::get(), memory::__rc_ptr_counted_data_base::throw_bad_weak_ptr(), and memory::enable_shared_rc_from_this< T >::weak_this_.
shared_from_this() [2/2]
template<class T > strong_rc_ptr< const T > memory::enable_shared_rc_from_this< T >::shared_from_this () const inline
Definition at line 1260 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::get(), memory::__rc_ptr_counted_data_base::throw_bad_weak_ptr(), and memory::enable_shared_rc_from_this< T >::weak_this_.
weak_from_this() [1/2]
template<class T > weak_rc_ptr< T > memory::enable_shared_rc_from_this< T >::weak_from_this () inline
Definition at line 1271 of file rc_ptr.h.
References memory::enable_shared_rc_from_this< T >::weak_this_.
weak_from_this() [2/2]
template<class T > weak_rc_ptr< const T > memory::enable_shared_rc_from_this< T >::weak_from_this () const inline
Definition at line 1273 of file rc_ptr.h.
References memory::enable_shared_rc_from_this< T >::weak_this_.
Friends And Related Symbol Documentation
strong_rc_ptr
template<class T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY strong_rc_ptr friend
Definition at line 1283 of file rc_ptr.h.
Field Documentation
weak_this_
template<class T > weak_rc_ptr<T> memory::enable_shared_rc_from_this< T >::weak_this_ mutable private
Definition at line 1292 of file rc_ptr.h.
Referenced by memory::enable_shared_rc_from_this< T >::__internal_weak_assign(), memory::enable_shared_rc_from_this< T >::shared_from_this(), memory::enable_shared_rc_from_this< T >::shared_from_this(), memory::enable_shared_rc_from_this< T >::weak_from_this(), and memory::enable_shared_rc_from_this< T >::weak_from_this().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h