libcopp: strong_rc Namespace Reference
strong_rc Namespace Reference
Namespaces
namespace n_access
namespace n_assignment
namespace n_comparison
namespace n_const_cast
namespace n_constructors
namespace n_element_type
namespace n_map
namespace n_report_1
namespace n_report_2
namespace n_reset
namespace n_spt_abstract
namespace n_spt_another_sp
namespace n_spt_array
namespace n_spt_incomplete
namespace n_spt_intrusive
namespace n_spt_pimpl
namespace n_spt_preventing_delete
namespace n_spt_shared_from_this
namespace n_spt_static
namespace n_spt_wrap
namespace n_static_cast
namespace n_swap
namespace n_transitive
namespace n_use_count
Functions
CASE_TEST (rc_ptr, strong_rc_basic)
Function Documentation
CASE_TEST()
strong_rc::CASE_TEST (rc_ptr , strong_rc_basic)
Definition at line 2517 of file rc_ptr_test.cpp.
References strong_rc::n_element_type::test(), strong_rc::n_constructors::test(), strong_rc::n_assignment::test(), strong_rc::n_reset::test(), strong_rc::n_access::test(), strong_rc::n_use_count::test(), strong_rc::n_swap::test(), strong_rc::n_comparison::test(), strong_rc::n_static_cast::test(), strong_rc::n_const_cast::test(), strong_rc::n_map::test(), strong_rc::n_transitive::test(), strong_rc::n_report_1::test(), strong_rc::n_report_2::test(), strong_rc::n_spt_incomplete::test(), strong_rc::n_spt_pimpl::test(), strong_rc::n_spt_abstract::test(), strong_rc::n_spt_preventing_delete::test(), strong_rc::n_spt_array::test(), strong_rc::n_spt_static::test(), strong_rc::n_spt_intrusive::test(), strong_rc::n_spt_another_sp::test(), strong_rc::n_spt_shared_from_this::test(), and strong_rc::n_spt_wrap::test().