libcopp: memory::weak_rc_ptr< T > Class Template Reference
memory::weak_rc_ptr< T > Class Template Reference
A std::weak_ptr replacement that is more lightweight and do not use atomic operation for reference counting.
#include <rc_ptr.h>
Public Types
using element_type = nostd::remove_extent_t< T >
Public Member Functions
constexpr weak_rc_ptr () noexcept
weak_rc_ptr (const weak_rc_ptr &) noexcept=default
weak_rc_ptr & operator= (const weak_rc_ptr &) noexcept=default
~weak_rc_ptr ()=default
weak_rc_ptr (weak_rc_ptr &&other) noexcept
weak_rc_ptr & operator= (weak_rc_ptr &&other) noexcept
template<class Y >
weak_rc_ptr (const strong_rc_ptr< Y > &other) noexcept
template<class Y >
weak_rc_ptr (const weak_rc_ptr< Y > &other) noexcept
template<class Y >
weak_rc_ptr (weak_rc_ptr< Y > &&other) noexcept
template<class Y >
weak_rc_ptr & operator= (const weak_rc_ptr< Y > &other) noexcept
template<class Y >
weak_rc_ptr & operator= (weak_rc_ptr< Y > &&other) noexcept
template<class Y >
weak_rc_ptr & operator= (const strong_rc_ptr< Y > &other) noexcept
void reset () noexcept
void swap (weak_rc_ptr &r) noexcept
std::size_t use_count () const noexcept
bool expired () const noexcept
strong_rc_ptr< T > lock () const noexcept
template<class Y >
bool owner_before (strong_rc_ptr< Y > const &r) const noexcept
template<class Y >
bool owner_before (weak_rc_ptr< Y > const &r) const noexcept
template<class Y >
bool owner_equal (strong_rc_ptr< Y > const &r) const noexcept
template<class Y >
bool owner_equal (weak_rc_ptr< Y > const &r) const noexcept
std::size_t owner_hash () const noexcept
Private Member Functions
void assign (element_type *__ptr, const __strong_rc_counter< T > &__refcount) noexcept
Private Attributes
element_type * ptr_
__weak_rc_counter< T > ref_counter_
Friends
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY enable_shared_rc_from_this
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY weak_rc_ptr
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY strong_rc_ptr
Detailed Description
template<typename T>
class memory::weak_rc_ptr< T >
A std::weak_ptr replacement that is more lightweight and do not use atomic operation for reference counting.
Note
This class is designed for single thread usage.
Definition at line 1131 of file rc_ptr.h.
Member Typedef Documentation
element_type
template<typename T > using memory::weak_rc_ptr< T >::element_type = nostd::remove_extent_t<T>
Definition at line 1133 of file rc_ptr.h.
Constructor & Destructor Documentation
weak_rc_ptr() [1/6]
template<typename T > constexpr memory::weak_rc_ptr< T >::weak_rc_ptr () inline constexpr noexcept
Definition at line 1136 of file rc_ptr.h.
weak_rc_ptr() [2/6]
template<typename T > memory::weak_rc_ptr< T >::weak_rc_ptr (const weak_rc_ptr< T > &) default noexcept
~weak_rc_ptr()
template<typename T > memory::weak_rc_ptr< T >::~weak_rc_ptr () default
weak_rc_ptr() [3/6]
template<typename T > memory::weak_rc_ptr< T >::weak_rc_ptr (weak_rc_ptr< T > && other) inline noexcept
Definition at line 1142 of file rc_ptr.h.
weak_rc_ptr() [4/6]
template<typename T > template<class Y > memory::weak_rc_ptr< T >::weak_rc_ptr (const strong_rc_ptr< Y > & other) inline noexcept
Definition at line 1153 of file rc_ptr.h.
weak_rc_ptr() [5/6]
template<typename T > template<class Y > memory::weak_rc_ptr< T >::weak_rc_ptr (const weak_rc_ptr< Y > & other) inline noexcept
Definition at line 1157 of file rc_ptr.h.
weak_rc_ptr() [6/6]
template<typename T > template<class Y > memory::weak_rc_ptr< T >::weak_rc_ptr (weak_rc_ptr< Y > && other) inline noexcept
Definition at line 1162 of file rc_ptr.h.
Member Function Documentation
assign()
template<typename T > void memory::weak_rc_ptr< T >::assign (element_type * __ptr, const __strong_rc_counter< T > & __refcount) inline private noexcept
Definition at line 1228 of file rc_ptr.h.
expired()
template<typename T > bool memory::weak_rc_ptr< T >::expired () const inline noexcept
Definition at line 1195 of file rc_ptr.h.
lock()
template<typename T > strong_rc_ptr< T > memory::weak_rc_ptr< T >::lock () const inline noexcept
Definition at line 1197 of file rc_ptr.h.
Referenced by memory::weak_rc_ptr< T >::operator=().
operator=() [1/5]
template<typename T > template<class Y > weak_rc_ptr & memory::weak_rc_ptr< T >::operator= (const strong_rc_ptr< Y > & other) inline noexcept
Definition at line 1180 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::ptr_, and memory::__weak_rc_counter< T >::swap().
operator=() [2/5]
template<typename T > weak_rc_ptr & memory::weak_rc_ptr< T >::operator= (const weak_rc_ptr< T > &) default noexcept
operator=() [3/5]
template<typename T > template<class Y > weak_rc_ptr & memory::weak_rc_ptr< T >::operator= (const weak_rc_ptr< Y > & other) inline noexcept
Definition at line 1167 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::lock().
operator=() [4/5]
template<typename T > weak_rc_ptr & memory::weak_rc_ptr< T >::operator= (weak_rc_ptr< T > && other) inline noexcept
Definition at line 1147 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::swap().
operator=() [5/5]
template<typename T > template<class Y > weak_rc_ptr & memory::weak_rc_ptr< T >::operator= (weak_rc_ptr< Y > && other) inline noexcept
Definition at line 1174 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::swap().
owner_before() [1/2]
template<typename T > template<class Y > bool memory::weak_rc_ptr< T >::owner_before (strong_rc_ptr< Y > const & r) const inline noexcept
Definition at line 1200 of file rc_ptr.h.
owner_before() [2/2]
template<typename T > template<class Y > bool memory::weak_rc_ptr< T >::owner_before (weak_rc_ptr< Y > const & r) const inline noexcept
Definition at line 1205 of file rc_ptr.h.
owner_equal() [1/2]
template<typename T > template<class Y > bool memory::weak_rc_ptr< T >::owner_equal (strong_rc_ptr< Y > const & r) const inline noexcept
Definition at line 1210 of file rc_ptr.h.
owner_equal() [2/2]
template<typename T > template<class Y > bool memory::weak_rc_ptr< T >::owner_equal (weak_rc_ptr< Y > const & r) const inline noexcept
Definition at line 1215 of file rc_ptr.h.
owner_hash()
template<typename T > std::size_t memory::weak_rc_ptr< T >::owner_hash () const inline noexcept
Definition at line 1219 of file rc_ptr.h.
reset()
template<typename T > void memory::weak_rc_ptr< T >::reset () inline noexcept
Definition at line 1186 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::swap().
swap()
template<typename T > void memory::weak_rc_ptr< T >::swap (weak_rc_ptr< T > & r) inline noexcept
Definition at line 1188 of file rc_ptr.h.
References std::swap().
Referenced by memory::weak_rc_ptr< T >::operator=(), memory::weak_rc_ptr< T >::operator=(), and memory::weak_rc_ptr< T >::reset().
use_count()
template<typename T > std::size_t memory::weak_rc_ptr< T >::use_count () const inline noexcept
Definition at line 1193 of file rc_ptr.h.
Friends And Related Symbol Documentation
enable_shared_rc_from_this
template<typename T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY enable_shared_rc_from_this friend
Definition at line 1225 of file rc_ptr.h.
strong_rc_ptr
template<typename T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY strong_rc_ptr friend
Definition at line 1239 of file rc_ptr.h.
weak_rc_ptr
template<typename T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY weak_rc_ptr friend
Definition at line 1236 of file rc_ptr.h.
Field Documentation
ptr_
template<typename T > element_type* memory::weak_rc_ptr< T >::ptr_ private
Definition at line 1242 of file rc_ptr.h.
Referenced by memory::weak_rc_ptr< T >::operator=(), memory::strong_rc_ptr< T >::strong_rc_ptr(), and memory::strong_rc_ptr< T >::strong_rc_ptr().
ref_counter_
template<typename T > __weak_rc_counter<T> memory::weak_rc_ptr< T >::ref_counter_ private
Definition at line 1243 of file rc_ptr.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h