libcopp: util Namespace Reference
util Namespace Reference
Namespaces
cli
details
lock
string
Data Structures
class intrusive_ptr
class uint64_id_allocator
Functions
template<typename T , typename U >
bool operator== (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator== (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator== (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator!= (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator!= (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator!= (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator< (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator< (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator< (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator<= (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator<= (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator<= (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator> (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator> (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator> (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator>= (intrusive_ptr< T > const &a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator>= (intrusive_ptr< T > const &a, U *b) LIBCOPP_MACRO_NOEXCEPT
template<typename T , typename U >
bool operator>= (T *a, intrusive_ptr< U > const &b) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator== (intrusive_ptr< T > const &p, std::nullptr_t) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator== (std::nullptr_t, intrusive_ptr< T > const &p) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator!= (intrusive_ptr< T > const &p, std::nullptr_t) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator!= (std::nullptr_t, intrusive_ptr< T > const &p) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator< (intrusive_ptr< T > const &p, std::nullptr_t) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator< (std::nullptr_t, intrusive_ptr< T > const &p) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator<= (intrusive_ptr< T > const &p, std::nullptr_t) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator<= (std::nullptr_t, intrusive_ptr< T > const &p) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator> (intrusive_ptr< T > const &p, std::nullptr_t) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator> (std::nullptr_t, intrusive_ptr< T > const &p) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator>= (intrusive_ptr< T > const &p, std::nullptr_t) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
bool operator>= (std::nullptr_t, intrusive_ptr< T > const &p) LIBCOPP_MACRO_NOEXCEPT
template<typename T >
void swap (intrusive_ptr< T > &lhs, intrusive_ptr< T > &rhs)
template<typename T >
T * get_pointer (intrusive_ptr< T > const &p)
template<typename T , typename U >
intrusive_ptr< T > static_pointer_cast (intrusive_ptr< U > const &p)
template<typename T , typename U >
intrusive_ptr< T > const_pointer_cast (intrusive_ptr< U > const &p)
template<typename E , typename T , typename Y >
std::basic_ostream< E, T > & operator<< (std::basic_ostream< E, T > &os, intrusive_ptr< Y > const &p)
Detailed Description
cmd_option_bind<TCmdStr>.h
Version: 2.0.0 Created on: 2011-12-29 Last edit : 2016-04-09 Author: OWenT
应用程序命令处理 注意: 除了类绑定的目标类外，所有默认的函数推断均是传值方式引入 并且数值的复制在执行bind_cmd时，如果需要引用需要显式指定函数类型 注意默认推导不支持隐式转换(即对double和int是默认推导，但float、short、long等需要指明参数类型) 为了更高效，所有返回值均为PDO类型和指针/智能指针
cmd_option_bind<TCmdStr>.h
Version: 2.0.0 Created on: 2011-12-29 Last edit : 2016-04-09 Author: OWenT
应用程序命令处理 快捷工具
特殊指令字符串类
Window 控制台相关
See also
https://msdn.microsoft.com/zh-cn/windows/apps/ms686047%28v=vs.100%29.aspx
https://github.com/owent-utils/python/blob/master/print_color.py
Function Documentation
const_pointer_cast()
template<typename T , typename U > intrusive_ptr<T> util::const_pointer_cast (intrusive_ptr< U > const & p)
Definition at line 356 of file intrusive_ptr.h.
References util::intrusive_ptr< T >::get().
get_pointer()
template<typename T > T* util::get_pointer (intrusive_ptr< T > const & p)
Definition at line 346 of file intrusive_ptr.h.
References util::intrusive_ptr< T >::get().
operator!=() [1/5]
template<typename T , typename U > bool util::operator!= (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 190 of file intrusive_ptr.h.
operator!=() [2/5]
template<typename T , typename U > bool util::operator!= (intrusive_ptr< T > const & a, U * b) inline
Definition at line 195 of file intrusive_ptr.h.
operator!=() [3/5]
template<typename T > bool util::operator!= (intrusive_ptr< T > const & p, std::nullptr_t) inline
Definition at line 288 of file intrusive_ptr.h.
operator!=() [4/5]
template<typename T > bool util::operator!= (std::nullptr_t , intrusive_ptr< T > const & p) inline
Definition at line 293 of file intrusive_ptr.h.
operator!=() [5/5]
template<typename T , typename U > bool util::operator!= (T * a, intrusive_ptr< U > const & b) inline
Definition at line 200 of file intrusive_ptr.h.
operator<() [1/5]
template<typename T , typename U > bool util::operator< (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 205 of file intrusive_ptr.h.
operator<() [2/5]
template<typename T , typename U > bool util::operator< (intrusive_ptr< T > const & a, U * b) inline
Definition at line 210 of file intrusive_ptr.h.
operator<() [3/5]
template<typename T > bool util::operator< (intrusive_ptr< T > const & p, std::nullptr_t) inline
Definition at line 298 of file intrusive_ptr.h.
operator<() [4/5]
template<typename T > bool util::operator< (std::nullptr_t , intrusive_ptr< T > const & p) inline
Definition at line 303 of file intrusive_ptr.h.
operator<() [5/5]
template<typename T , typename U > bool util::operator< (T * a, intrusive_ptr< U > const & b) inline
Definition at line 215 of file intrusive_ptr.h.
operator<<()
template<typename E , typename T , typename Y > std::basic_ostream<E, T>& util::operator<< (std::basic_ostream< E, T > & os, intrusive_ptr< Y > const & p)
Definition at line 356 of file intrusive_ptr.h.
operator<=() [1/5]
template<typename T , typename U > bool util::operator<= (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 220 of file intrusive_ptr.h.
operator<=() [2/5]
template<typename T , typename U > bool util::operator<= (intrusive_ptr< T > const & a, U * b) inline
Definition at line 225 of file intrusive_ptr.h.
operator<=() [3/5]
template<typename T > bool util::operator<= (intrusive_ptr< T > const & p, std::nullptr_t) inline
Definition at line 308 of file intrusive_ptr.h.
operator<=() [4/5]
template<typename T > bool util::operator<= (std::nullptr_t , intrusive_ptr< T > const & p) inline
Definition at line 313 of file intrusive_ptr.h.
operator<=() [5/5]
template<typename T , typename U > bool util::operator<= (T * a, intrusive_ptr< U > const & b) inline
Definition at line 230 of file intrusive_ptr.h.
operator==() [1/5]
template<typename T , typename U > bool util::operator== (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 159 of file intrusive_ptr.h.
operator==() [2/5]
template<typename T , typename U > bool util::operator== (intrusive_ptr< T > const & a, U * b) inline
Definition at line 164 of file intrusive_ptr.h.
operator==() [3/5]
template<typename T > bool util::operator== (intrusive_ptr< T > const & p, std::nullptr_t) inline
Definition at line 267 of file intrusive_ptr.h.
operator==() [4/5]
template<typename T > bool util::operator== (std::nullptr_t , intrusive_ptr< T > const & p) inline
Definition at line 272 of file intrusive_ptr.h.
operator==() [5/5]
template<typename T , typename U > bool util::operator== (T * a, intrusive_ptr< U > const & b) inline
Definition at line 169 of file intrusive_ptr.h.
operator>() [1/5]
template<typename T , typename U > bool util::operator> (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 235 of file intrusive_ptr.h.
operator>() [2/5]
template<typename T , typename U > bool util::operator> (intrusive_ptr< T > const & a, U * b) inline
Definition at line 240 of file intrusive_ptr.h.
operator>() [3/5]
template<typename T > bool util::operator> (intrusive_ptr< T > const & p, std::nullptr_t) inline
Definition at line 318 of file intrusive_ptr.h.
operator>() [4/5]
template<typename T > bool util::operator> (std::nullptr_t , intrusive_ptr< T > const & p) inline
Definition at line 323 of file intrusive_ptr.h.
operator>() [5/5]
template<typename T , typename U > bool util::operator> (T * a, intrusive_ptr< U > const & b) inline
Definition at line 245 of file intrusive_ptr.h.
operator>=() [1/5]
template<typename T , typename U > bool util::operator>= (intrusive_ptr< T > const & a, intrusive_ptr< U > const & b) inline
Definition at line 250 of file intrusive_ptr.h.
operator>=() [2/5]
template<typename T , typename U > bool util::operator>= (intrusive_ptr< T > const & a, U * b) inline
Definition at line 255 of file intrusive_ptr.h.
operator>=() [3/5]
template<typename T > bool util::operator>= (intrusive_ptr< T > const & p, std::nullptr_t) inline
Definition at line 328 of file intrusive_ptr.h.
operator>=() [4/5]
template<typename T > bool util::operator>= (std::nullptr_t , intrusive_ptr< T > const & p) inline
Definition at line 333 of file intrusive_ptr.h.
operator>=() [5/5]
template<typename T , typename U > bool util::operator>= (T * a, intrusive_ptr< U > const & b) inline
Definition at line 260 of file intrusive_ptr.h.
static_pointer_cast()
template<typename T , typename U > intrusive_ptr<T> util::static_pointer_cast (intrusive_ptr< U > const & p)
Definition at line 351 of file intrusive_ptr.h.
References util::intrusive_ptr< T >::get().
swap()
template<typename T > void util::swap (intrusive_ptr< T > & lhs, intrusive_ptr< T > & rhs)
Definition at line 339 of file intrusive_ptr.h.
References util::intrusive_ptr< T >::swap().
Referenced by CASE_TEST(), future::result_base< TOK, TERR, false >::operator=(), allocator::stack_allocator_memory::operator=(), future::result_base< TOK, TERR, false >::result_base(), allocator::stack_allocator_memory::stack_allocator_memory(), coroutine_context::start(), future::result_base< TOK, TERR, true >::swap(), future::result_base< TOK, TERR, false >::swap(), future::poller< T, TPTR >::swap(), allocator::stack_allocator_memory::swap(), and future::poll_storage_base< T, TPTR >::swap().