libcopp: memory::__strong_rc_counter< T > Class Template Reference
memory::__strong_rc_counter< T > Class Template Reference
#include <rc_ptr.h>
Data Structures
struct __not_alloc_shared_tag
struct __not_alloc_shared_tag< __strong_rc_default_alloc_shared_tag< Y > >
struct __not_alloc_shared_tag< __strong_rc_with_alloc_shared_tag< Y > >
Public Member Functions
constexpr __strong_rc_counter () noexcept
template<class Y >
__strong_rc_counter (Y *p)
template<class Y , class Deleter , class = typename __not_alloc_shared_tag<nostd::remove_cvref_t<Deleter>>::type>
__strong_rc_counter (Y *p, Deleter &&d)
template<class Y , class Deleter , class Alloc , class = typename __not_alloc_shared_tag<nostd::remove_cvref_t<Deleter>>::type>
__strong_rc_counter (Y *p, Deleter &&d, Alloc &&a)
template<class... Args>
__strong_rc_counter (T *&__p, __strong_rc_default_alloc_shared_tag< T >, Args &&... args)
template<class Alloc , class... Args>
__strong_rc_counter (T *&__p, __strong_rc_with_alloc_shared_tag< T >, Alloc &&a, Args &&... args)
template<class UT , class UDeleter >
__strong_rc_counter (std::unique_ptr< UT, UDeleter > &&r)
__strong_rc_counter (const __weak_rc_counter< T > &w)
__strong_rc_counter (const __weak_rc_counter< T > &w, std::nothrow_t) noexcept
~__strong_rc_counter ()
__strong_rc_counter (const __strong_rc_counter &r) noexcept
__strong_rc_counter (__strong_rc_counter &&r) noexcept
template<class Y >
__strong_rc_counter (const __strong_rc_counter< Y > &r) noexcept
template<class Y >
__strong_rc_counter (__strong_rc_counter< Y > &&r) noexcept
__strong_rc_counter & operator= (const __strong_rc_counter &r) noexcept
__strong_rc_counter & operator= (__strong_rc_counter &&r) noexcept
void swap (__strong_rc_counter &r) noexcept
template<class Y >
void swap (__strong_rc_counter< Y > &r) noexcept
std::size_t use_count () const noexcept
__rc_ptr_counted_data_base * ref_counter () const noexcept
Private Attributes
__rc_ptr_counted_data_base * pi_
Friends
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY __strong_rc_counter
Detailed Description
template<class T>
class memory::__strong_rc_counter< T >
Definition at line 323 of file rc_ptr.h.
Constructor & Destructor Documentation
__strong_rc_counter() [1/13]
template<class T > constexpr memory::__strong_rc_counter< T >::__strong_rc_counter () inline constexpr noexcept
Definition at line 338 of file rc_ptr.h.
__strong_rc_counter() [2/13]
template<class T > template<class Y > memory::__strong_rc_counter< T >::__strong_rc_counter (Y * p) inline explicit
Definition at line 341 of file rc_ptr.h.
References memory::allocate_guarded().
__strong_rc_counter() [3/13]
template<class T > template<class Y , class Deleter , class = typename __not_alloc_shared_tag<nostd::remove_cvref_t<Deleter>>::type> memory::__strong_rc_counter< T >::__strong_rc_counter (Y * p, Deleter && d) inline
Definition at line 369 of file rc_ptr.h.
References memory::allocate_guarded().
__strong_rc_counter() [4/13]
template<class T > template<class Y , class Deleter , class Alloc , class = typename __not_alloc_shared_tag<nostd::remove_cvref_t<Deleter>>::type> memory::__strong_rc_counter< T >::__strong_rc_counter (Y * p, Deleter && d, Alloc && a) inline
Definition at line 390 of file rc_ptr.h.
References memory::allocate_guarded().
__strong_rc_counter() [5/13]
template<class T > template<class... Args> memory::__strong_rc_counter< T >::__strong_rc_counter (T *& __p, __strong_rc_default_alloc_shared_tag< T > , Args &&... args) inline
Definition at line 412 of file rc_ptr.h.
References memory::allocate_guarded().
__strong_rc_counter() [6/13]
template<class T > template<class Alloc , class... Args> memory::__strong_rc_counter< T >::__strong_rc_counter (T *& __p, __strong_rc_with_alloc_shared_tag< T > , Alloc && a, Args &&... args) inline
Definition at line 433 of file rc_ptr.h.
References memory::allocate_guarded().
__strong_rc_counter() [7/13]
template<class T > template<class UT , class UDeleter > memory::__strong_rc_counter< T >::__strong_rc_counter (std::unique_ptr< UT, UDeleter > && r) inline explicit
Definition at line 457 of file rc_ptr.h.
References memory::allocate_guarded().
__strong_rc_counter() [8/13]
template<class T > memory::__strong_rc_counter< T >::__strong_rc_counter (const __weak_rc_counter< T > & w) explicit
Definition at line 655 of file rc_ptr.h.
References memory::__rc_ptr_counted_data_base::add_ref_nothrow(), memory::__strong_rc_counter< T >::pi_, and memory::__rc_ptr_counted_data_base::throw_bad_weak_ptr().
__strong_rc_counter() [9/13]
template<class T > memory::__strong_rc_counter< T >::__strong_rc_counter (const __weak_rc_counter< T > & w, std::nothrow_t) noexcept
Definition at line 663 of file rc_ptr.h.
~__strong_rc_counter()
template<class T > memory::__strong_rc_counter< T >::~__strong_rc_counter () inline
Definition at line 486 of file rc_ptr.h.
__strong_rc_counter() [10/13]
template<class T > memory::__strong_rc_counter< T >::__strong_rc_counter (const __strong_rc_counter< T > & r) inline noexcept
Definition at line 492 of file rc_ptr.h.
__strong_rc_counter() [11/13]
template<class T > memory::__strong_rc_counter< T >::__strong_rc_counter (__strong_rc_counter< T > && r) inline noexcept
Definition at line 498 of file rc_ptr.h.
__strong_rc_counter() [12/13]
template<class T > template<class Y > memory::__strong_rc_counter< T >::__strong_rc_counter (const __strong_rc_counter< Y > & r) inline noexcept
Definition at line 501 of file rc_ptr.h.
__strong_rc_counter() [13/13]
template<class T > template<class Y > memory::__strong_rc_counter< T >::__strong_rc_counter (__strong_rc_counter< Y > && r) inline noexcept
Definition at line 508 of file rc_ptr.h.
Member Function Documentation
operator=() [1/2]
template<class T > __strong_rc_counter & memory::__strong_rc_counter< T >::operator= (__strong_rc_counter< T > && r) inline noexcept
Definition at line 527 of file rc_ptr.h.
References memory::__rc_ptr_counted_data_base::release().
operator=() [2/2]
template<class T > __strong_rc_counter & memory::__strong_rc_counter< T >::operator= (const __strong_rc_counter< T > & r) inline noexcept
Definition at line 512 of file rc_ptr.h.
References memory::__rc_ptr_counted_data_base::add_ref(), and memory::__rc_ptr_counted_data_base::release().
ref_counter()
template<class T > __rc_ptr_counted_data_base * memory::__strong_rc_counter< T >::ref_counter () const inline noexcept
Definition at line 555 of file rc_ptr.h.
swap() [1/2]
template<class T > void memory::__strong_rc_counter< T >::swap (__strong_rc_counter< T > & r) inline noexcept
Definition at line 540 of file rc_ptr.h.
swap() [2/2]
template<class T > template<class Y > void memory::__strong_rc_counter< T >::swap (__strong_rc_counter< Y > & r) inline noexcept
Definition at line 547 of file rc_ptr.h.
use_count()
template<class T > std::size_t memory::__strong_rc_counter< T >::use_count () const inline noexcept
Definition at line 553 of file rc_ptr.h.
Friends And Related Symbol Documentation
__strong_rc_counter
template<class T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY __strong_rc_counter friend
Definition at line 559 of file rc_ptr.h.
Field Documentation
pi_
template<class T > __rc_ptr_counted_data_base* memory::__strong_rc_counter< T >::pi_ private
Definition at line 561 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::__strong_rc_counter().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h