libcopp: weak_rc::n_constructors Namespace Reference
weak_rc::n_constructors Namespace Reference
Functions
void default_constructor ()
void shared_ptr_constructor ()
void copy_constructor ()
void conversion_constructor ()
void test ()
Function Documentation
conversion_constructor()
void weak_rc::n_constructors::conversion_constructor ()
Definition at line 3214 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, and weak_rc::create_incomplete().
Referenced by test().
copy_constructor()
void weak_rc::n_constructors::copy_constructor ()
Definition at line 3101 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, and weak_rc::create_incomplete().
Referenced by test().
default_constructor()
void weak_rc::n_constructors::default_constructor ()
Definition at line 2956 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE.
Referenced by test().
shared_ptr_constructor()
void weak_rc::n_constructors::shared_ptr_constructor ()
Definition at line 2973 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, and weak_rc::create_incomplete().
Referenced by test().
test()
void weak_rc::n_constructors::test ()
Definition at line 3368 of file rc_ptr_test.cpp.
References conversion_constructor(), copy_constructor(), default_constructor(), and shared_ptr_constructor().
Referenced by weak_rc::CASE_TEST().