libcopp: task_action_mem_function< Ty, Tc > Class Template Reference
task_action_mem_function< Ty, Tc > Class Template Reference
#include <task_actions.h>
Data Structures
struct invoker
struct invoker< Tz, false >
struct invoker< Tz, true >
Public Types
using value_type = Ty Tc::*
Public Member Functions
task_action_mem_function (value_type func, Tc *inst)
~task_action_mem_function ()
int operator() (void *priv_data) override
virtual int on_finished (task_impl &)
Static Public Member Functions
static void placement_destroy (void *selfp)
Private Attributes
Tc * instacne_
value_type func_
Detailed Description
template<typename Ty, typename Tc>
class task_action_mem_function< Ty, Tc >
Definition at line 145 of file task_actions.h.
Member Typedef Documentation
value_type
template<typename Ty , typename Tc > using task_action_mem_function< Ty, Tc >::value_type = Ty Tc::*
Definition at line 147 of file task_actions.h.
Constructor & Destructor Documentation
task_action_mem_function()
template<typename Ty , typename Tc > task_action_mem_function< Ty, Tc >::task_action_mem_function (value_type func, Tc * inst) inline
Definition at line 169 of file task_actions.h.
~task_action_mem_function()
template<typename Ty , typename Tc > task_action_mem_function< Ty, Tc >::~task_action_mem_function () inline
Definition at line 170 of file task_actions.h.
Referenced by task_action_mem_function< Ty, Tc >::placement_destroy().
Member Function Documentation
on_finished()
LIBCOPP_COTASK_API int impl::task_action_impl::on_finished (task_impl &) virtual inherited
Definition at line 19 of file task_action_impl.cpp.
Referenced by impl::task_impl::_notify_finished().
operator()()
template<typename Ty , typename Tc > int task_action_mem_function< Ty, Tc >::operator() (void * priv_data) inline override virtual
Implements impl::task_action_impl.
Definition at line 172 of file task_actions.h.
placement_destroy()
template<typename Ty , typename Tc > static void task_action_mem_function< Ty, Tc >::placement_destroy (void * selfp) inline static
Definition at line 176 of file task_actions.h.
References task_action_mem_function< Ty, Tc >::~task_action_mem_function().
Field Documentation
func_
template<typename Ty , typename Tc > value_type task_action_mem_function< Ty, Tc >::func_ private
Definition at line 187 of file task_actions.h.
Referenced by task_action_mem_function< Ty, Tc >::invoker< Tz, true >::invoke(), and task_action_mem_function< Ty, Tc >::invoker< Tz, false >::invoke().
instacne_
template<typename Ty , typename Tc > Tc* task_action_mem_function< Ty, Tc >::instacne_ private
Definition at line 186 of file task_actions.h.
Referenced by task_action_mem_function< Ty, Tc >::invoker< Tz, true >::invoke(), and task_action_mem_function< Ty, Tc >::invoker< Tz, false >::invoke().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcotask/task_actions.h