libcopp: /home/runner/work/libcopp/libcopp/test/case/coroutine_context_this_coroutine_test.cpp File Reference
coroutine_context_this_coroutine_test.cpp File Reference
#include "frame/test_macros.h"
#include <assert.h>
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <atomic>
#include <chrono>
#include <functional>
#include <memory>
#include <thread>
#include <vector>
#include <libcopp/coroutine/coroutine_context_container.h>
#include <libcotask/task.h>
Data Structures
class test_this_context_get_cotoutine_runner
class test_this_context_yield_runner
struct test_this_context_rec_runner
struct test_this_context_start_failed_when_running
Functions
static void test_this_context_thread_func (copp::coroutine_context_default::ptr_t co, test_this_context_get_cotoutine_runner *runner)
CASE_TEST (this_context, get_coroutine)
CASE_TEST (this_context, yield_)
CASE_TEST (this_context, start_in_co)
CASE_TEST (this_context, start_failed_when_running)
Function Documentation
CASE_TEST() [1/4]
CASE_TEST (this_context , get_coroutine)
Definition at line 78 of file coroutine_context_this_coroutine_test.cpp.
References CASE_EXPECT_LT, co_arr, test_this_context_get_cotoutine_runner::get_max_thd_count(), and test_this_context_thread_func().
CASE_TEST() [2/4]
CASE_TEST (this_context , start_failed_when_running)
Definition at line 245 of file coroutine_context_this_coroutine_test.cpp.
References test_this_context_start_failed_when_running::is_start.
CASE_TEST() [3/4]
CASE_TEST (this_context , start_in_co)
Definition at line 188 of file coroutine_context_this_coroutine_test.cpp.
References CASE_EXPECT_EQ, this_coroutine::get_coroutine(), test_this_context_rec_runner::has_resume, test_this_context_rec_runner::has_yield, test_this_context_rec_runner::jump_to, and test_this_context_rec_runner::owner.
CASE_TEST() [4/4]
CASE_TEST (this_context , yield_)
Definition at line 123 of file coroutine_context_this_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, this_coroutine::get_coroutine(), test_this_context_yield_runner::is_finished(), and test_this_context_yield_runner::is_run().
test_this_context_thread_func()
static void test_this_context_thread_func (copp::coroutine_context_default::ptr_t co, test_this_context_get_cotoutine_runner * runner) static
Definition at line 65 of file coroutine_context_this_coroutine_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, this_coroutine::get_coroutine(), test_this_context_get_cotoutine_runner::is_run(), and test_this_context_get_cotoutine_runner::set_co_obj().
Referenced by CASE_TEST().