libcopp: strong_rc::n_spt_intrusive Namespace Reference
strong_rc::n_spt_intrusive Namespace Reference
Data Structures
struct intrusive_deleter
struct X
Functions
void intrusive_ptr_add_ref (X *p)
void intrusive_ptr_release (X *p)
copp::memory::strong_rc_ptr< X > make_shared_from_intrusive (X *p)
void test ()
Variables
int X_instances = 0
Function Documentation
intrusive_ptr_add_ref()
void strong_rc::n_spt_intrusive::intrusive_ptr_add_ref (X * p)
Definition at line 2317 of file rc_ptr_test.cpp.
References strong_rc::n_spt_intrusive::X::count.
Referenced by make_shared_from_intrusive().
intrusive_ptr_release()
void strong_rc::n_spt_intrusive::intrusive_ptr_release (X * p)
Definition at line 2319 of file rc_ptr_test.cpp.
References strong_rc::n_spt_intrusive::X::count.
Referenced by strong_rc::n_spt_intrusive::intrusive_deleter< T >::operator()().
make_shared_from_intrusive()
copp::memory::strong_rc_ptr< X > strong_rc::n_spt_intrusive::make_shared_from_intrusive (X * p)
Definition at line 2330 of file rc_ptr_test.cpp.
References intrusive_ptr_add_ref().
Referenced by test().
test()
void strong_rc::n_spt_intrusive::test ()
Definition at line 2336 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, strong_rc::n_spt_intrusive::X::count, make_shared_from_intrusive(), and X_instances.
Referenced by strong_rc::CASE_TEST().
Variable Documentation
X_instances
int strong_rc::n_spt_intrusive::X_instances = 0
Definition at line 2307 of file rc_ptr_test.cpp.
Referenced by test(), strong_rc::n_spt_intrusive::X::X(), and strong_rc::n_spt_intrusive::X::~X().