libcopp: test_on_start_base Class Reference
test_on_start_base Class Reference
#include <test_case_base.h>
Public Types
typedef void(* on_start_func) ()
Public Member Functions
typedef UTIL_UNIT_TEST_MACRO_AUTO_SET (std::string) after_set_t
template<typename... T>
test_on_start_base (const std::string &n, on_start_func func, T &&... deps)
template<typename... T>
void expand (T &&...)
virtual ~test_on_start_base ()
virtual int run ()
Data Fields
std::string name
on_start_func func_
after_set_t after
Private Member Functions
void register_self ()
Detailed Description
Definition at line 53 of file test_case_base.h.
Member Typedef Documentation
on_start_func
typedef void(* test_on_start_base::on_start_func) ()
Definition at line 56 of file test_case_base.h.
Constructor & Destructor Documentation
test_on_start_base()
template<typename... T> test_on_start_base::test_on_start_base (const std::string & n, on_start_func func, T &&... deps) inline
Definition at line 60 of file test_case_base.h.
References after, expand(), and register_self().
~test_on_start_base()
test_on_start_base::~test_on_start_base () virtual
Definition at line 44 of file test_case_base.cpp.
Member Function Documentation
expand()
template<typename... T> void test_on_start_base::expand (T && ...) inline
Definition at line 67 of file test_case_base.h.
Referenced by test_on_start_base().
register_self()
void test_on_start_base::register_self () private
Definition at line 42 of file test_case_base.cpp.
References test_manager::append_event_on_start(), test_manager::me(), and name.
Referenced by test_on_start_base().
run()
int test_on_start_base::run () virtual
Definition at line 46 of file test_case_base.cpp.
References func_.
UTIL_UNIT_TEST_MACRO_AUTO_SET()
typedef test_on_start_base::UTIL_UNIT_TEST_MACRO_AUTO_SET (std::string)
Field Documentation
after
after_set_t test_on_start_base::after
Definition at line 75 of file test_case_base.h.
Referenced by test_on_start_base().
func_
on_start_func test_on_start_base::func_
Definition at line 74 of file test_case_base.h.
Referenced by run().
name
std::string test_on_start_base::name
Definition at line 73 of file test_case_base.h.
Referenced by register_self().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.h
/home/runner/work/libcopp/libcopp/test/frame/test_case_base.cpp