libcopp: memory::strong_rc_ptr< T > Class Template Reference
memory::strong_rc_ptr< T > Class Template Reference
A std::shared_ptr replacement that is more lightweight and do not use atomic operation for reference counting.
#include <rc_ptr.h>
Public Types
using element_type = nostd::remove_extent_t< T >
using weak_type = weak_rc_ptr< T >
using nullability_compatible_type = void
using absl_nullability_compatible = void
Public Member Functions
constexpr strong_rc_ptr () noexcept
constexpr strong_rc_ptr (std::nullptr_t) noexcept
template<class Y >
strong_rc_ptr (Y *ptr) noexcept
template<class Y , class Deleter >
strong_rc_ptr (Y *ptr, Deleter d)
template<class Y , class Deleter , class Alloc >
strong_rc_ptr (Y *ptr, Deleter d, Alloc a)
template<class Deleter >
strong_rc_ptr (std::nullptr_t ptr, Deleter d)
template<class Y , class Deleter , class Alloc >
strong_rc_ptr (std::nullptr_t ptr, Deleter d, Alloc a)
template<class Y >
strong_rc_ptr (const strong_rc_ptr< Y > &other) noexcept
template<class Y >
strong_rc_ptr (strong_rc_ptr< Y > &&other) noexcept
template<class Y >
strong_rc_ptr (const strong_rc_ptr< Y > &other, element_type *ptr) noexcept
template<class Y >
strong_rc_ptr (strong_rc_ptr< Y > &&other, element_type *ptr) noexcept
strong_rc_ptr (const weak_rc_ptr< T > &other)
strong_rc_ptr (const weak_rc_ptr< T > &other, std::nothrow_t) noexcept
template<class Y >
strong_rc_ptr (const weak_rc_ptr< Y > &other)
template<class Y , class Deleter >
strong_rc_ptr (std::unique_ptr< Y, Deleter > &&other)
template<class... Args>
strong_rc_ptr (__strong_rc_default_alloc_shared_tag< T > __tag, Args &&... args)
This is a special constructor for make_strong_rc/allocate_strong_rc.
template<class... Args>
strong_rc_ptr (__strong_rc_with_alloc_shared_tag< T > __tag, Args &&... args)
This is a special constructor for make_strong_rc/allocate_strong_rc.
~strong_rc_ptr () noexcept=default
strong_rc_ptr (const strong_rc_ptr &) noexcept=default
strong_rc_ptr & operator= (const strong_rc_ptr &) noexcept=default
strong_rc_ptr (strong_rc_ptr &&other) noexcept
strong_rc_ptr & operator= (strong_rc_ptr &&other) noexcept
template<class Y >
strong_rc_ptr & operator= (const strong_rc_ptr< Y > &other) noexcept
template<class Y >
strong_rc_ptr & operator= (strong_rc_ptr< Y > &&other) noexcept
template<class Y , class Deleter >
strong_rc_ptr & operator= (std::unique_ptr< Y, Deleter > &&other)
void reset () noexcept
template<class Y >
void reset (Y *ptr) noexcept
template<class Y , class Deleter >
void reset (Y *ptr, Deleter d) noexcept
template<class Y , class Deleter , class Alloc >
void reset (Y *ptr, Deleter d, Alloc a) noexcept
void swap (strong_rc_ptr &other) noexcept
element_type * get () const noexcept
std::size_t use_count () const noexcept
bool unique () const noexcept
operator bool () const noexcept
template<class Y >
bool owner_before (strong_rc_ptr< Y > const &r) const noexcept
template<class Y >
bool owner_before (weak_rc_ptr< Y > const &r) const noexcept
template<class Y >
bool owner_equal (strong_rc_ptr< Y > const &r) const noexcept
template<class Y >
bool owner_equal (weak_rc_ptr< Y > const &r) const noexcept
std::size_t owner_hash () const noexcept
element_type & operator* () const noexcept
element_type * operator-> () const noexcept
Private Attributes
element_type * ptr_
__strong_rc_counter< element_type > ref_counter_
Friends
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY weak_rc_ptr
template<class >
class LIBCOPP_COPP_API_HEAD_ONLY strong_rc_ptr
Detailed Description
template<class T>
class memory::strong_rc_ptr< T >
A std::shared_ptr replacement that is more lightweight and do not use atomic operation for reference counting.
Note
This class is designed for single thread usage.
Definition at line 791 of file rc_ptr.h.
Member Typedef Documentation
absl_nullability_compatible
template<class T > using memory::strong_rc_ptr< T >::absl_nullability_compatible = void
Definition at line 798 of file rc_ptr.h.
element_type
template<class T > using memory::strong_rc_ptr< T >::element_type = nostd::remove_extent_t<T>
Definition at line 793 of file rc_ptr.h.
nullability_compatible_type
template<class T > using memory::strong_rc_ptr< T >::nullability_compatible_type = void
Definition at line 797 of file rc_ptr.h.
weak_type
template<class T > using memory::strong_rc_ptr< T >::weak_type = weak_rc_ptr<T>
Definition at line 794 of file rc_ptr.h.
Constructor & Destructor Documentation
strong_rc_ptr() [1/19]
template<class T > constexpr memory::strong_rc_ptr< T >::strong_rc_ptr () inline constexpr noexcept
Definition at line 801 of file rc_ptr.h.
strong_rc_ptr() [2/19]
template<class T > constexpr memory::strong_rc_ptr< T >::strong_rc_ptr (std::nullptr_t) inline constexpr noexcept
Definition at line 803 of file rc_ptr.h.
strong_rc_ptr() [3/19]
template<class T > template<class Y > memory::strong_rc_ptr< T >::strong_rc_ptr (Y * ptr) inline noexcept
Definition at line 806 of file rc_ptr.h.
References memory::__enable_shared_from_this_with().
strong_rc_ptr() [4/19]
template<class T > template<class Y , class Deleter > memory::strong_rc_ptr< T >::strong_rc_ptr (Y * ptr, Deleter d) inline
Definition at line 814 of file rc_ptr.h.
References memory::__enable_shared_from_this_with().
strong_rc_ptr() [5/19]
template<class T > template<class Y , class Deleter , class Alloc > memory::strong_rc_ptr< T >::strong_rc_ptr (Y * ptr, Deleter d, Alloc a) inline
Definition at line 819 of file rc_ptr.h.
References memory::__enable_shared_from_this_with().
strong_rc_ptr() [6/19]
template<class T > template<class Deleter > memory::strong_rc_ptr< T >::strong_rc_ptr (std::nullptr_t ptr, Deleter d) inline
Definition at line 824 of file rc_ptr.h.
strong_rc_ptr() [7/19]
template<class T > template<class Y , class Deleter , class Alloc > memory::strong_rc_ptr< T >::strong_rc_ptr (std::nullptr_t ptr, Deleter d, Alloc a) inline
Definition at line 827 of file rc_ptr.h.
strong_rc_ptr() [8/19]
template<class T > template<class Y > memory::strong_rc_ptr< T >::strong_rc_ptr (const strong_rc_ptr< Y > & other) inline noexcept
Definition at line 830 of file rc_ptr.h.
strong_rc_ptr() [9/19]
template<class T > template<class Y > memory::strong_rc_ptr< T >::strong_rc_ptr (strong_rc_ptr< Y > && other) inline noexcept
Definition at line 833 of file rc_ptr.h.
strong_rc_ptr() [10/19]
template<class T > template<class Y > memory::strong_rc_ptr< T >::strong_rc_ptr (const strong_rc_ptr< Y > & other, element_type * ptr) inline noexcept
Definition at line 839 of file rc_ptr.h.
strong_rc_ptr() [11/19]
template<class T > template<class Y > memory::strong_rc_ptr< T >::strong_rc_ptr (strong_rc_ptr< Y > && other, element_type * ptr) inline noexcept
Definition at line 843 of file rc_ptr.h.
strong_rc_ptr() [12/19]
template<class T > memory::strong_rc_ptr< T >::strong_rc_ptr (const weak_rc_ptr< T > & other) inline
Definition at line 848 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::ptr_.
strong_rc_ptr() [13/19]
template<class T > memory::strong_rc_ptr< T >::strong_rc_ptr (const weak_rc_ptr< T > & other, std::nothrow_t) inline noexcept
Definition at line 853 of file rc_ptr.h.
strong_rc_ptr() [14/19]
template<class T > template<class Y > memory::strong_rc_ptr< T >::strong_rc_ptr (const weak_rc_ptr< Y > & other) inline
Definition at line 859 of file rc_ptr.h.
References memory::weak_rc_ptr< T >::ptr_.
strong_rc_ptr() [15/19]
template<class T > template<class Y , class Deleter > memory::strong_rc_ptr< T >::strong_rc_ptr (std::unique_ptr< Y, Deleter > && other) inline
Definition at line 865 of file rc_ptr.h.
References memory::__enable_shared_from_this_with().
strong_rc_ptr() [16/19]
template<class T > template<class... Args> memory::strong_rc_ptr< T >::strong_rc_ptr (__strong_rc_default_alloc_shared_tag< T > __tag, Args &&... args) inline
This is a special constructor for make_strong_rc/allocate_strong_rc.
Parameters
__tag Tag for type decetion
args Arguments to construct the object.
Definition at line 877 of file rc_ptr.h.
References memory::__enable_shared_from_this_with().
strong_rc_ptr() [17/19]
template<class T > template<class... Args> memory::strong_rc_ptr< T >::strong_rc_ptr (__strong_rc_with_alloc_shared_tag< T > __tag, Args &&... args) inline
This is a special constructor for make_strong_rc/allocate_strong_rc.
Parameters
__tag Tag for type decetion
args Arguments to construct the object.
Definition at line 888 of file rc_ptr.h.
References memory::__enable_shared_from_this_with().
~strong_rc_ptr()
template<class T > memory::strong_rc_ptr< T >::~strong_rc_ptr () default noexcept
strong_rc_ptr() [18/19]
template<class T > memory::strong_rc_ptr< T >::strong_rc_ptr (const strong_rc_ptr< T > &) explicit default noexcept
strong_rc_ptr() [19/19]
template<class T > memory::strong_rc_ptr< T >::strong_rc_ptr (strong_rc_ptr< T > && other) inline explicit noexcept
Definition at line 897 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
Member Function Documentation
get()
template<class T > element_type * memory::strong_rc_ptr< T >::get () const inline noexcept
Definition at line 952 of file rc_ptr.h.
Referenced by memory::enable_shared_rc_from_this< T >::shared_from_this(), and memory::enable_shared_rc_from_this< T >::shared_from_this().
operator bool()
template<class T > memory::strong_rc_ptr< T >::operator bool () const inline explicit noexcept
Definition at line 958 of file rc_ptr.h.
operator*()
template<class T , bool = std::is_array<T>::value, bool = std::is_void<T>::value> element_type & memory::strong_rc_ptr_access< T, bool, bool >::operator* () const inline noexcept inherited
Definition at line 678 of file rc_ptr.h.
operator->()
template<class T , bool = std::is_array<T>::value, bool = std::is_void<T>::value> element_type * memory::strong_rc_ptr_access< T, bool, bool >::operator-> () const inline noexcept inherited
Definition at line 688 of file rc_ptr.h.
operator=() [1/5]
template<class T > strong_rc_ptr & memory::strong_rc_ptr< T >::operator= (const strong_rc_ptr< T > &) default noexcept
operator=() [2/5]
template<class T > template<class Y > strong_rc_ptr & memory::strong_rc_ptr< T >::operator= (const strong_rc_ptr< Y > & other) inline noexcept
Definition at line 908 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::ptr_.
operator=() [3/5]
template<class T > template<class Y , class Deleter > strong_rc_ptr & memory::strong_rc_ptr< T >::operator= (std::unique_ptr< Y, Deleter > && other) inline
Definition at line 921 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
operator=() [4/5]
template<class T > strong_rc_ptr & memory::strong_rc_ptr< T >::operator= (strong_rc_ptr< T > && other) inline noexcept
Definition at line 902 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
operator=() [5/5]
template<class T > template<class Y > strong_rc_ptr & memory::strong_rc_ptr< T >::operator= (strong_rc_ptr< Y > && other) inline noexcept
Definition at line 915 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
owner_before() [1/2]
template<class T > template<class Y > bool memory::strong_rc_ptr< T >::owner_before (strong_rc_ptr< Y > const & r) const inline noexcept
Definition at line 961 of file rc_ptr.h.
owner_before() [2/2]
template<class T > template<class Y > bool memory::strong_rc_ptr< T >::owner_before (weak_rc_ptr< Y > const & r) const inline noexcept
Definition at line 966 of file rc_ptr.h.
owner_equal() [1/2]
template<class T > template<class Y > bool memory::strong_rc_ptr< T >::owner_equal (strong_rc_ptr< Y > const & r) const inline noexcept
Definition at line 971 of file rc_ptr.h.
owner_equal() [2/2]
template<class T > template<class Y > bool memory::strong_rc_ptr< T >::owner_equal (weak_rc_ptr< Y > const & r) const inline noexcept
Definition at line 976 of file rc_ptr.h.
owner_hash()
template<class T > std::size_t memory::strong_rc_ptr< T >::owner_hash () const inline noexcept
Definition at line 980 of file rc_ptr.h.
reset() [1/4]
template<class T > void memory::strong_rc_ptr< T >::reset () inline noexcept
Definition at line 926 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
reset() [2/4]
template<class T > template<class Y > void memory::strong_rc_ptr< T >::reset (Y * ptr) inline noexcept
Definition at line 929 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
reset() [3/4]
template<class T > template<class Y , class Deleter > void memory::strong_rc_ptr< T >::reset (Y * ptr, Deleter d) inline noexcept
Definition at line 938 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
reset() [4/4]
template<class T > template<class Y , class Deleter , class Alloc > void memory::strong_rc_ptr< T >::reset (Y * ptr, Deleter d, Alloc a) inline noexcept
Definition at line 943 of file rc_ptr.h.
References memory::strong_rc_ptr< T >::swap().
swap()
template<class T > void memory::strong_rc_ptr< T >::swap (strong_rc_ptr< T > & other) inline noexcept
Definition at line 947 of file rc_ptr.h.
References std::swap().
Referenced by memory::strong_rc_ptr< T >::operator=(), memory::strong_rc_ptr< T >::operator=(), memory::strong_rc_ptr< T >::operator=(), memory::strong_rc_ptr< T >::reset(), memory::strong_rc_ptr< T >::reset(), memory::strong_rc_ptr< T >::reset(), memory::strong_rc_ptr< T >::reset(), and memory::strong_rc_ptr< T >::strong_rc_ptr().
unique()
template<class T > bool memory::strong_rc_ptr< T >::unique () const inline noexcept
Definition at line 956 of file rc_ptr.h.
use_count()
template<class T > std::size_t memory::strong_rc_ptr< T >::use_count () const inline noexcept
Definition at line 954 of file rc_ptr.h.
Friends And Related Symbol Documentation
strong_rc_ptr
template<class T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY strong_rc_ptr friend
Definition at line 989 of file rc_ptr.h.
weak_rc_ptr
template<class T > template<class > friend class LIBCOPP_COPP_API_HEAD_ONLY weak_rc_ptr friend
Definition at line 986 of file rc_ptr.h.
Field Documentation
ptr_
template<class T > element_type* memory::strong_rc_ptr< T >::ptr_ private
Definition at line 992 of file rc_ptr.h.
Referenced by memory::strong_rc_ptr< T >::operator=().
ref_counter_
template<class T > __strong_rc_counter<element_type> memory::strong_rc_ptr< T >::ref_counter_ private
Definition at line 993 of file rc_ptr.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h