libcopp: weak_rc Namespace Reference
weak_rc Namespace Reference
Namespaces
namespace n_assignment
namespace n_constructors
namespace n_element_type
namespace n_lock
namespace n_reset
namespace n_swap
namespace n_use_count
Data Structures
class incomplete
struct X
struct Y
struct Z
Functions
copp::memory::strong_rc_ptr< incomplete > create_incomplete ()
CASE_TEST (rc_ptr, weak_rc_ptr_basic)
Function Documentation
CASE_TEST()
weak_rc::CASE_TEST (rc_ptr , weak_rc_ptr_basic)
Definition at line 3850 of file rc_ptr_test.cpp.
References weak_rc::n_element_type::test(), weak_rc::n_constructors::test(), weak_rc::n_assignment::test(), weak_rc::n_reset::test(), weak_rc::n_use_count::test(), weak_rc::n_swap::test(), and weak_rc::n_lock::test().
create_incomplete()
copp::memory::strong_rc_ptr< incomplete > weak_rc::create_incomplete ()
Definition at line 3862 of file rc_ptr_test.cpp.
Referenced by weak_rc::n_assignment::conversion_assignment(), weak_rc::n_constructors::conversion_constructor(), weak_rc::n_constructors::copy_constructor(), weak_rc::n_constructors::shared_ptr_constructor(), weak_rc::n_assignment::test(), and weak_rc::n_reset::test().