libcopp: strong_rc::n_spt_incomplete Namespace Reference
strong_rc::n_spt_incomplete Namespace Reference
Data Structures
class file
Functions
copp::memory::strong_rc_ptr< file > fopen (char const *name, char const *mode)
void fread (copp::memory::strong_rc_ptr< file > f, void *data, int64_t size)
void test ()
Variables
int file_instances = 0
Function Documentation
fopen()
copp::memory::strong_rc_ptr< file > strong_rc::n_spt_incomplete::fopen (char const * name, char const * mode) private
Definition at line 2564 of file rc_ptr_test.cpp.
Referenced by test().
fread()
void strong_rc::n_spt_incomplete::fread (copp::memory::strong_rc_ptr< file > f, void * data, int64_t size) private
Definition at line 2569 of file rc_ptr_test.cpp.
Referenced by test().
test()
void strong_rc::n_spt_incomplete::test () private
Definition at line 2126 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, file_instances, fopen(), and fread().
Referenced by strong_rc::CASE_TEST().
Variable Documentation
file_instances
int strong_rc::n_spt_incomplete::file_instances = 0 private
Definition at line 2124 of file rc_ptr_test.cpp.
Referenced by strong_rc::n_spt_incomplete::file::file(), test(), and strong_rc::n_spt_incomplete::file::~file().