libcopp: allocator::stack_allocator_windows Class Reference
allocator::stack_allocator_windows Class Reference
memory allocator this allocator will create buffer using windows api and protect it
#include <stack_allocator_windows.h>
Public Member Functions
stack_allocator_windows () LIBCOPP_MACRO_NOEXCEPT
~stack_allocator_windows ()
stack_allocator_windows (const stack_allocator_windows &other) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_windows & operator= (const stack_allocator_windows &other) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_windows (stack_allocator_windows &&other) LIBCOPP_MACRO_NOEXCEPT
stack_allocator_windows & operator= (stack_allocator_windows &&other) LIBCOPP_MACRO_NOEXCEPT
void allocate (stack_context &, std::size_t) LIBCOPP_MACRO_NOEXCEPT
void deallocate (stack_context &) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
memory allocator this allocator will create buffer using windows api and protect it
Definition at line 24 of file stack_allocator_windows.h.
Constructor & Destructor Documentation
stack_allocator_windows() [1/3]
LIBCOPP_COPP_API allocator::stack_allocator_windows::stack_allocator_windows ()
Definition at line 41 of file stack_allocator_windows.cpp.
~stack_allocator_windows()
LIBCOPP_COPP_API allocator::stack_allocator_windows::~stack_allocator_windows ()
Definition at line 42 of file stack_allocator_windows.cpp.
stack_allocator_windows() [2/3]
LIBCOPP_COPP_API allocator::stack_allocator_windows::stack_allocator_windows (const stack_allocator_windows & other)
Definition at line 43 of file stack_allocator_windows.cpp.
stack_allocator_windows() [3/3]
LIBCOPP_COPP_API allocator::stack_allocator_windows::stack_allocator_windows (stack_allocator_windows && other)
Definition at line 50 of file stack_allocator_windows.cpp.
Member Function Documentation
allocate()
LIBCOPP_COPP_API void allocator::stack_allocator_windows::allocate (stack_context & ctx, std::size_t size)
allocate memory and attach to stack context [standard function]
Parameters
ctx stack context
size stack size
Definition at line 56 of file stack_allocator_windows.cpp.
References stack_traits::is_unbounded(), stack_traits::maximum_size(), stack_traits::minimum_size(), stack_traits::page_size(), and stack_traits::round_to_page_size().
deallocate()
LIBCOPP_COPP_API void allocator::stack_allocator_windows::deallocate (stack_context & ctx)
deallocate memory from stack context [standard function]
Parameters
ctx stack context
Definition at line 77 of file stack_allocator_windows.cpp.
References stack_traits::is_unbounded(), stack_traits::maximum_size(), and stack_traits::minimum_size().
operator=() [1/2]
LIBCOPP_COPP_API stack_allocator_windows & allocator::stack_allocator_windows::operator= (const stack_allocator_windows & other)
Definition at line 45 of file stack_allocator_windows.cpp.
operator=() [2/2]
LIBCOPP_COPP_API stack_allocator_windows & allocator::stack_allocator_windows::operator= (stack_allocator_windows && other)
Definition at line 51 of file stack_allocator_windows.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/stack/allocator/stack_allocator_windows.h
/home/runner/work/libcopp/libcopp/src/libcopp/stack/allocator/stack_allocator_windows.cpp