libcopp: memory::__rc_ptr_counted_data_base Class Reference
memory::__rc_ptr_counted_data_base Class Reference abstract
#include <rc_ptr.h>
Public Member Functions
constexpr __rc_ptr_counted_data_base () noexcept
virtual LIBCOPP_COPP_API ~__rc_ptr_counted_data_base () noexcept
virtual void dispose () noexcept=0
virtual void destroy () noexcept=0
LIBCOPP_UTIL_FORCEINLINE void add_ref ()
LIBCOPP_UTIL_FORCEINLINE bool add_ref_nothrow () noexcept
LIBCOPP_UTIL_FORCEINLINE void release () noexcept
LIBCOPP_UTIL_FORCEINLINE void weak_add_ref () noexcept
LIBCOPP_UTIL_FORCEINLINE void weak_release () noexcept
LIBCOPP_UTIL_FORCEINLINE std::size_t use_count () const noexcept
Static Public Member Functions
static LIBCOPP_COPP_API void throw_bad_weak_ptr ()
Private Member Functions
__rc_ptr_counted_data_base (const __rc_ptr_counted_data_base &)=delete
__rc_ptr_counted_data_base & operator= (const __rc_ptr_counted_data_base &)=delete
Private Attributes
std::size_t use_count_
std::size_t weak_count_
Detailed Description
Definition at line 37 of file rc_ptr.h.
Constructor & Destructor Documentation
__rc_ptr_counted_data_base() [1/2]
constexpr memory::__rc_ptr_counted_data_base::__rc_ptr_counted_data_base () inline constexpr noexcept
Definition at line 39 of file rc_ptr.h.
~__rc_ptr_counted_data_base()
LIBCOPP_COPP_API memory::__rc_ptr_counted_data_base::~__rc_ptr_counted_data_base () virtual noexcept
Definition at line 11 of file rc_ptr.cpp.
__rc_ptr_counted_data_base() [2/2]
memory::__rc_ptr_counted_data_base::__rc_ptr_counted_data_base (const __rc_ptr_counted_data_base &) private delete
Member Function Documentation
add_ref()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::add_ref () inline
Definition at line 54 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::operator=().
add_ref_nothrow()
LIBCOPP_UTIL_FORCEINLINE bool memory::__rc_ptr_counted_data_base::add_ref_nothrow () inline noexcept
Definition at line 61 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::__strong_rc_counter().
destroy()
virtual void memory::__rc_ptr_counted_data_base::destroy () pure virtual noexcept
Implemented in memory::__rc_ptr_counted_data_default< T >, memory::__rc_ptr_counted_data_inplace< T >, memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >, memory::__rc_ptr_counted_data_with_deleter< T, Deleter >, and memory::__rc_ptr_counted_data_with_deleter_allocator< T, Deleter, Alloc >.
dispose()
virtual void memory::__rc_ptr_counted_data_base::dispose () pure virtual noexcept
Implemented in memory::__rc_ptr_counted_data_default< T >, memory::__rc_ptr_counted_data_inplace< T >, memory::__rc_ptr_counted_data_inplace_alloc< T, Alloc >, memory::__rc_ptr_counted_data_with_deleter< T, Deleter >, and memory::__rc_ptr_counted_data_with_deleter_allocator< T, Deleter, Alloc >.
operator=()
__rc_ptr_counted_data_base & memory::__rc_ptr_counted_data_base::operator= (const __rc_ptr_counted_data_base &) private delete
release()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::release () inline noexcept
Definition at line 71 of file rc_ptr.h.
Referenced by memory::__strong_rc_counter< T >::operator=(), and memory::__strong_rc_counter< T >::operator=().
throw_bad_weak_ptr()
LIBCOPP_COPP_API void memory::__rc_ptr_counted_data_base::throw_bad_weak_ptr () static
Definition at line 13 of file rc_ptr.cpp.
Referenced by memory::__strong_rc_counter< T >::__strong_rc_counter(), memory::enable_shared_rc_from_this< T >::shared_from_this(), and memory::enable_shared_rc_from_this< T >::shared_from_this().
use_count()
LIBCOPP_UTIL_FORCEINLINE std::size_t memory::__rc_ptr_counted_data_base::use_count () const inline noexcept
Definition at line 90 of file rc_ptr.h.
weak_add_ref()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::weak_add_ref () inline noexcept
Definition at line 81 of file rc_ptr.h.
Referenced by memory::__weak_rc_counter< T >::operator=().
weak_release()
LIBCOPP_UTIL_FORCEINLINE void memory::__rc_ptr_counted_data_base::weak_release () inline noexcept
Definition at line 84 of file rc_ptr.h.
Referenced by memory::__weak_rc_counter< T >::operator=(), and memory::__weak_rc_counter< T >::operator=().
Field Documentation
use_count_
std::size_t memory::__rc_ptr_counted_data_base::use_count_ private
Definition at line 97 of file rc_ptr.h.
weak_count_
std::size_t memory::__rc_ptr_counted_data_base::weak_count_ private
Definition at line 98 of file rc_ptr.h.
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/rc_ptr.h
/home/runner/work/libcopp/libcopp/src/libcopp/utils/memory/rc_ptr.cpp