libcopp: this_coroutine Namespace Reference
this_coroutine Namespace Reference
Functions
LIBCOPP_COPP_API coroutine_context * get_coroutine () LIBCOPP_MACRO_NOEXCEPT
get current coroutine
template<typename Tc >
LIBCOPP_COPP_API_HEAD_ONLY Tc * get ()
get current coroutine and try to convert type
LIBCOPP_COPP_API int yield (void **priv_data=nullptr) LIBCOPP_MACRO_NOEXCEPT
yield current coroutine
Function Documentation
get()
template<typename Tc > LIBCOPP_COPP_API_HEAD_ONLY Tc* this_coroutine::get ()
get current coroutine and try to convert type
See also
get_coroutine
detail::coroutine_context
Returns
pointer of current coroutine, if not in coroutine or fail to convert type, return nullptr
Definition at line 159 of file coroutine_context.h.
References get_coroutine().
Referenced by task< TCO_MACRO >::await_task().
get_coroutine()
LIBCOPP_COPP_API coroutine_context * this_coroutine::get_coroutine ()
get current coroutine
See also
detail::coroutine_context
Returns
pointer of current coroutine, if not in coroutine, return nullptr
Definition at line 467 of file coroutine_context.cpp.
References coroutine_context_base::check_flags(), coroutine_context_base::flag_type::EN_CFT_IS_FIBER, and detail::get_this_coroutine_context().
Referenced by CASE_TEST(), get(), my_runner(), test_this_context_rec_runner::operator()(), test_this_context_get_cotoutine_runner::operator()(), coroutine_context::start(), test_this_context_thread_func(), and yield().
yield()
LIBCOPP_COPP_API int this_coroutine::yield (void ** priv_data = nullptr)
yield current coroutine
Parameters
priv_data private data, if not nullptr, will get the value from start(priv_data) or resume(priv_data)
Returns
0 or error code
Definition at line 477 of file coroutine_context.cpp.
References COPP_EC_NOT_RUNNING, COPP_LIKELY_IF, get_coroutine(), detail::get_this_coroutine_context(), and coroutine_context::yield().
Referenced by test_this_context_yield_runner::operator()().