libcopp: strong_rc::n_constructors Namespace Reference
strong_rc::n_constructors Namespace Reference
Data Structures
struct A
struct deleter3
struct X
struct Y
Functions
void default_constructor ()
template<class T >
void pc0_test (T *p)
void pointer_constructor ()
void deleter (int *p)
void deleter2 (int *p)
void deleter_constructor ()
void copy_constructor ()
void weak_ptr_constructor ()
void test ()
Variables
int m = 0
incomplete * p0 = 0
Function Documentation
copy_constructor()
void strong_rc::n_constructors::copy_constructor ()
Definition at line 463 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, strong_rc::n_constructors::X::instances, and strong_rc::n_constructors::Y::instances.
Referenced by test().
default_constructor()
void strong_rc::n_constructors::default_constructor ()
Definition at line 52 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE.
Referenced by test().
deleter()
void strong_rc::n_constructors::deleter (int * p)
Definition at line 346 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE.
Referenced by deleter_constructor().
deleter2()
void strong_rc::n_constructors::deleter2 (int * p)
Definition at line 348 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, and m.
Referenced by deleter_constructor().
deleter_constructor()
void strong_rc::n_constructors::deleter_constructor ()
Definition at line 361 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, deleter(), deleter2(), m, and p0.
Referenced by test().
pc0_test()
template<class T > void strong_rc::n_constructors::pc0_test (T * p)
Definition at line 113 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE.
Referenced by pointer_constructor().
pointer_constructor()
void strong_rc::n_constructors::pointer_constructor ()
Definition at line 123 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, strong_rc::n_constructors::X::instances, strong_rc::n_constructors::Y::instances, and pc0_test().
Referenced by test().
test()
void strong_rc::n_constructors::test ()
Definition at line 796 of file rc_ptr_test.cpp.
References copy_constructor(), default_constructor(), deleter_constructor(), pointer_constructor(), and weak_ptr_constructor().
Referenced by strong_rc::CASE_TEST().
weak_ptr_constructor()
void strong_rc::n_constructors::weak_ptr_constructor ()
Definition at line 714 of file rc_ptr_test.cpp.
References CASE_EXPECT_ERROR, and CASE_EXPECT_TRUE.
Referenced by test().
Variable Documentation
m
int strong_rc::n_constructors::m = 0
Definition at line 344 of file rc_ptr_test.cpp.
Referenced by deleter2(), and deleter_constructor().
p0
incomplete* strong_rc::n_constructors::p0 = 0
Definition at line 359 of file rc_ptr_test.cpp.
Referenced by deleter_constructor().