libcopp: task_action_function< Ty > Class Template Reference
task_action_function< Ty > Class Template Reference
#include <task_actions.h>
Data Structures
struct invoker
struct invoker< Tz, false >
struct invoker< Tz, true >
Public Types
using value_type = Ty(*)(void *)
Public Member Functions
task_action_function (value_type func)
~task_action_function ()
int operator() (void *priv_data) override
virtual int on_finished (task_impl &)
Static Public Member Functions
static void placement_destroy (void *selfp)
Private Attributes
value_type func_
Detailed Description
template<typename Ty>
class task_action_function< Ty >
Definition at line 99 of file task_actions.h.
Member Typedef Documentation
value_type
template<typename Ty > using task_action_function< Ty >::value_type = Ty (*)(void *)
Definition at line 101 of file task_actions.h.
Constructor & Destructor Documentation
task_action_function()
template<typename Ty > task_action_function< Ty >::task_action_function (value_type func) inline
Definition at line 123 of file task_actions.h.
~task_action_function()
template<typename Ty > task_action_function< Ty >::~task_action_function () inline
Definition at line 124 of file task_actions.h.
Referenced by task_action_function< Ty >::placement_destroy().
Member Function Documentation
on_finished()
LIBCOPP_COTASK_API int impl::task_action_impl::on_finished (task_impl &) virtual inherited
Definition at line 19 of file task_action_impl.cpp.
Referenced by impl::task_impl::_notify_finished().
operator()()
template<typename Ty > int task_action_function< Ty >::operator() (void * priv_data) inline override virtual
Implements impl::task_action_impl.
Definition at line 126 of file task_actions.h.
placement_destroy()
template<typename Ty > static void task_action_function< Ty >::placement_destroy (void * selfp) inline static
Definition at line 130 of file task_actions.h.
References task_action_function< Ty >::~task_action_function().
Field Documentation
func_
template<typename Ty > value_type task_action_function< Ty >::func_ private
Definition at line 140 of file task_actions.h.
Referenced by task_action_function< Ty >::invoker< Tz, true >::invoke(), and task_action_function< Ty >::invoker< Tz, false >::invoke().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcotask/task_actions.h