libcopp: strong_rc::n_reset Namespace Reference
strong_rc::n_reset Namespace Reference
Data Structures
struct A
struct X
struct Y
Functions
void deleter (incomplete *)
void plain_reset ()
void pointer_reset ()
void deleter2 (void *p)
void deleter_reset ()
void test ()
Variables
incomplete * p0 = 0
void * deleted = 0
Function Documentation
deleter()
void strong_rc::n_reset::deleter (incomplete *) private
Definition at line 1067 of file rc_ptr_test.cpp.
Referenced by plain_reset().
deleter2()
void strong_rc::n_reset::deleter2 (void * p) private
Definition at line 1319 of file rc_ptr_test.cpp.
References deleted.
Referenced by deleter_reset().
deleter_reset()
void strong_rc::n_reset::deleter_reset () private
Definition at line 1321 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, deleted, deleter2(), and p0.
Referenced by test().
plain_reset()
void strong_rc::n_reset::plain_reset () private
Definition at line 1083 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, deleter(), strong_rc::n_reset::X::instances, and p0.
Referenced by test().
pointer_reset()
void strong_rc::n_reset::pointer_reset () private
Definition at line 1190 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, strong_rc::n_reset::X::instances, and strong_rc::n_reset::Y::instances.
Referenced by test().
test()
void strong_rc::n_reset::test () private
Definition at line 1471 of file rc_ptr_test.cpp.
References deleter_reset(), plain_reset(), and pointer_reset().
Referenced by strong_rc::CASE_TEST().
Variable Documentation
deleted
void* strong_rc::n_reset::deleted = 0 private
Definition at line 1317 of file rc_ptr_test.cpp.
Referenced by deleter2(), and deleter_reset().
p0
incomplete* strong_rc::n_reset::p0 = 0 private
Definition at line 1065 of file rc_ptr_test.cpp.
Referenced by deleter_reset(), and plain_reset().