var searchData=
[
  ['sample_5fmacro_5fcoroutine_0',['sample_macro_coroutine',['../d4/dbb/structsample__macro__coroutine.html',1,'']]],
  ['set_5fconst_5ft_1',['set_const_t',['../da/dda/structutil_1_1cli_1_1phoenix_1_1set__const__t.html',1,'util::cli::phoenix']]],
  ['shell_5ffont_2',['shell_font',['../df/d41/classutil_1_1cli_1_1shell__font.html',1,'util::cli']]],
  ['shell_5ffont_5fstyle_3',['shell_font_style',['../d6/d92/structutil_1_1cli_1_1shell__font__style.html',1,'util::cli']]],
  ['shell_5fstream_4',['shell_stream',['../d7/db4/classutil_1_1cli_1_1shell__stream.html',1,'util::cli']]],
  ['shell_5fstream_5fopr_5',['shell_stream_opr',['../dc/d58/classutil_1_1cli_1_1shell__stream_1_1shell__stream__opr.html',1,'util::cli::shell_stream']]],
  ['small_5fobject_5foptimize_5fstorage_5fdeleter_6',['small_object_optimize_storage_deleter',['../d5/dd1/structfuture_1_1small__object__optimize__storage__deleter.html',1,'future']]],
  ['smart_5fpointer_5fdeleter_7',['smart_pointer_deleter',['../de/d9f/classstrong__rc_1_1n__spt__another__sp_1_1smart__pointer__deleter.html',1,'strong_rc::n_spt_another_sp']]],
  ['span_8',['span',['../d9/d1f/classgsl_1_1span.html',1,'gsl']]],
  ['span_3c_20t_2c_20dynamic_5fextent_20_3e_9',['span&lt; T, dynamic_extent &gt;',['../dd/d88/classgsl_1_1span_3_01T_00_01dynamic__extent_01_4.html',1,'gsl']]],
  ['spin_5flock_10',['spin_lock',['../da/db3/classutil_1_1lock_1_1spin__lock.html',1,'util::lock']]],
  ['stack_5fallocator_5fmalloc_11',['stack_allocator_malloc',['../d8/d7a/classallocator_1_1stack__allocator__malloc.html',1,'allocator']]],
  ['stack_5fallocator_5fmemory_12',['stack_allocator_memory',['../df/d92/classallocator_1_1stack__allocator__memory.html',1,'allocator']]],
  ['stack_5fallocator_5fpool_13',['stack_allocator_pool',['../dd/dc4/classallocator_1_1stack__allocator__pool.html',1,'allocator']]],
  ['stack_5fallocator_5fposix_14',['stack_allocator_posix',['../db/db1/classallocator_1_1stack__allocator__posix.html',1,'allocator']]],
  ['stack_5fallocator_5fsplit_5fsegment_15',['stack_allocator_split_segment',['../d8/d83/classallocator_1_1stack__allocator__split__segment.html',1,'allocator']]],
  ['stack_5fallocator_5fwindows_16',['stack_allocator_windows',['../df/dca/classallocator_1_1stack__allocator__windows.html',1,'allocator']]],
  ['stack_5fcontext_17',['stack_context',['../db/dde/structstack__context.html',1,'']]],
  ['stack_5fpool_18',['stack_pool',['../d5/db6/classstack__pool.html',1,'']]],
  ['stack_5fpool_5ftest_5fmacro_5fcoroutine_19',['stack_pool_test_macro_coroutine',['../d4/d45/structstack__pool__test__macro__coroutine.html',1,'']]],
  ['stack_5ft_20',['stack_t',['../d7/d45/structfcontext_1_1stack__t.html',1,'fcontext']]],
  ['stack_5ftraits_21',['stack_traits',['../d9/df0/structstack__traits.html',1,'']]],
  ['stackful_5fchannel_5fcontext_22',['stackful_channel_context',['../da/ddd/classstackful__channel__context.html',1,'']]],
  ['stackful_5fchannel_5fcontext_5fbase_23',['stackful_channel_context_base',['../d6/df9/classstackful__channel__context__base.html',1,'']]],
  ['stackful_5fchannel_5ferror_5ftransform_24',['stackful_channel_error_transform',['../de/df5/structstackful__channel__error__transform.html',1,'']]],
  ['stackful_5fchannel_5fhandle_5fdelegate_25',['stackful_channel_handle_delegate',['../d9/dcc/structstackful__channel__handle__delegate.html',1,'']]],
  ['stackful_5fchannel_5fhandle_5fdelegate_5fhash_26',['stackful_channel_handle_delegate_hash',['../da/d57/structstackful__channel__handle__delegate__hash.html',1,'']]],
  ['stackful_5fchannel_5freceiver_27',['stackful_channel_receiver',['../dd/d39/classstackful__channel__receiver.html',1,'']]],
  ['stackful_5fchannel_5fresume_5fhandle_28',['stackful_channel_resume_handle',['../df/dfa/structstackful__channel__resume__handle.html',1,'']]],
  ['stackful_5fchannel_5fresume_5fhandle_3c_20coroutine_5fcontext_20_3e_29',['stackful_channel_resume_handle&lt; coroutine_context &gt;',['../d0/d0f/structstackful__channel__resume__handle_3_01coroutine__context_01_4.html',1,'']]],
  ['stackful_5fchannel_5fresume_5fhandle_3c_20libcopp_5fcotask_5fnamespace_5fid_3a_3atask_3c_20tco_5fmacro_20_3e_20_3e_30',['stackful_channel_resume_handle&lt; LIBCOPP_COTASK_NAMESPACE_ID::task&lt; TCO_MACRO &gt; &gt;',['../d1/df9/structstackful__channel__resume__handle_3_01LIBCOPP__COTASK__NAMESPACE__ID_1_1task_3_01TCO__MACRO_01_4_01_4.html',1,'']]],
  ['stackful_5fchannel_5fresume_5finvoker_31',['stackful_channel_resume_invoker',['../d7/dd7/structstackful__channel__resume__invoker.html',1,'']]],
  ['stackful_5fchannel_5fsender_32',['stackful_channel_sender',['../d1/df1/classstackful__channel__sender.html',1,'']]],
  ['stackful_5finject_5fawaitable_33',['stackful_inject_awaitable',['../dd/d53/structstackful__inject__awaitable.html',1,'']]],
  ['stackful_5finject_5fawaitable_3c_20stackful_5fchannel_5freceiver_3c_20tvalue_20_3e_20_3e_34',['stackful_inject_awaitable&lt; stackful_channel_receiver&lt; TVALUE &gt; &gt;',['../da/d7a/structstackful__inject__awaitable_3_01stackful__channel__receiver_3_01TVALUE_01_4_01_4.html',1,'']]],
  ['standard_5fnew_5fallocator_35',['standard_new_allocator',['../d4/d80/classcore_1_1standard__new__allocator.html',1,'core']]],
  ['status_5ftype_36',['status_type',['../dc/d74/structcoroutine__context__base_1_1status__type.html',1,'coroutine_context_base']]],
  ['strict_5fnot_5fnull_37',['strict_not_null',['../d3/d90/classgsl_1_1strict__not__null.html',1,'gsl']]],
  ['string2any_38',['string2any',['../d1/d21/structutil_1_1cli_1_1string2any.html',1,'util::cli']]],
  ['string2any_3c_20bool_20_3e_39',['string2any&lt; bool &gt;',['../de/ddf/structutil_1_1cli_1_1string2any_3_01bool_01_4.html',1,'util::cli']]],
  ['string2any_3c_20char_20_3e_40',['string2any&lt; char &gt;',['../dd/d6c/structutil_1_1cli_1_1string2any_3_01char_01_4.html',1,'util::cli']]],
  ['string2any_3c_20int16_5ft_20_3e_41',['string2any&lt; int16_t &gt;',['../d0/db8/structutil_1_1cli_1_1string2any_3_01int16__t_01_4.html',1,'util::cli']]],
  ['string2any_3c_20int32_5ft_20_3e_42',['string2any&lt; int32_t &gt;',['../de/ddb/structutil_1_1cli_1_1string2any_3_01int32__t_01_4.html',1,'util::cli']]],
  ['string2any_3c_20int64_5ft_20_3e_43',['string2any&lt; int64_t &gt;',['../da/dbe/structutil_1_1cli_1_1string2any_3_01int64__t_01_4.html',1,'util::cli']]],
  ['string2any_3c_20std_3a_3astring_20_3e_44',['string2any&lt; std::string &gt;',['../d4/dc7/structutil_1_1cli_1_1string2any_3_01std_1_1string_01_4.html',1,'util::cli']]],
  ['string2any_3c_20uint16_5ft_20_3e_45',['string2any&lt; uint16_t &gt;',['../dc/d22/structutil_1_1cli_1_1string2any_3_01uint16__t_01_4.html',1,'util::cli']]],
  ['string2any_3c_20uint32_5ft_20_3e_46',['string2any&lt; uint32_t &gt;',['../df/d35/structutil_1_1cli_1_1string2any_3_01uint32__t_01_4.html',1,'util::cli']]],
  ['string2any_3c_20uint64_5ft_20_3e_47',['string2any&lt; uint64_t &gt;',['../dd/dd5/structutil_1_1cli_1_1string2any_3_01uint64__t_01_4.html',1,'util::cli']]],
  ['string2any_3c_20unsigned_20char_20_3e_48',['string2any&lt; unsigned char &gt;',['../db/dbe/structutil_1_1cli_1_1string2any_3_01unsigned_01char_01_4.html',1,'util::cli']]],
  ['strong_5frc_5fptr_49',['strong_rc_ptr',['../d9/de1/classmemory_1_1strong__rc__ptr.html',1,'memory']]],
  ['strong_5frc_5fptr_5faccess_50',['strong_rc_ptr_access',['../d6/d39/classmemory_1_1strong__rc__ptr__access.html',1,'memory']]],
  ['strong_5frc_5fptr_5faccess_3c_20t_2c_20false_2c_20true_20_3e_51',['strong_rc_ptr_access&lt; T, false, true &gt;',['../dd/d4c/classmemory_1_1strong__rc__ptr__access_3_01T_00_01false_00_01true_01_4.html',1,'memory']]],
  ['strong_5frc_5fptr_5faccess_3c_20t_2c_20true_2c_20false_20_3e_52',['strong_rc_ptr_access&lt; T, true, false &gt;',['../d4/d72/classmemory_1_1strong__rc__ptr__access_3_01T_00_01true_00_01false_01_4.html',1,'memory']]]
];
