libcopp: nostd::details Namespace Reference
nostd::details Namespace Reference
Data Structures
struct __inv_unwrap
struct __inv_unwrap< _Tp, ::std::reference_wrapper< _Up > >
struct __invoke_memfun_deref
struct __invoke_memfun_ref
struct __invoke_memobj_deref
struct __invoke_memobj_ref
struct __invoke_other
struct __invoke_tag
struct __result_of_tag_impl
struct __result_of_tag_impl< false, true, _MemPtr, _Clazz, _ArgTypes... >
struct __result_of_tag_impl< true, false, _MemPtr, _Clazz, _ArgTypes... >
Functions
template<typename _Tp , typename _Up = typename __inv_unwrap<_Tp>::type>
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR _Up && __invfwd (typename ::std::remove_reference< _Tp >::type &__t) noexcept
template<typename R , typename _Fn , typename... _Args>
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R __invoke_impl (__invoke_other, _Fn &&__f, _Args &&... __args)
template<typename R , typename _MemFun , typename _Tp , typename... _Args>
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R __invoke_impl (__invoke_memfun_ref, _MemFun &&__f, _Tp &&__t, _Args &&... __args)
template<typename R , typename _MemFun , typename _Tp , typename... _Args>
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R __invoke_impl (__invoke_memfun_deref, _MemFun &&__f, _Tp &&__t, _Args &&... __args)
template<typename R , typename _MemPtr , typename _Tp >
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R __invoke_impl (__invoke_memobj_ref, _MemPtr &&__f, _Tp &&__t)
template<typename R , typename _MemPtr , typename _Tp >
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R __invoke_impl (__invoke_memobj_deref, _MemPtr &&__f, _Tp &&__t)
template<typename F , typename... ArgTypes>
LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR invoke_result_t< F, ArgTypes... > __invoke (F &&__fn, ArgTypes &&... __args)
Function Documentation
__invfwd()
template<typename _Tp , typename _Up = typename __inv_unwrap<_Tp>::type> LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR _Up && nostd::details::__invfwd (typename ::std::remove_reference< _Tp >::type & __t) inline noexcept
Definition at line 123 of file type_traits.h.
__invoke()
template<typename F , typename... ArgTypes> LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR invoke_result_t< F, ArgTypes... > nostd::details::__invoke (F && __fn, ArgTypes &&... __args) inline
Definition at line 187 of file type_traits.h.
References __invoke_impl().
Referenced by nostd::invoke().
__invoke_impl() [1/5]
template<typename R , typename _MemFun , typename _Tp , typename... _Args> LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R nostd::details::__invoke_impl (__invoke_memfun_deref , _MemFun && __f, _Tp && __t, _Args &&... __args) inline
Definition at line 142 of file type_traits.h.
__invoke_impl() [2/5]
template<typename R , typename _MemFun , typename _Tp , typename... _Args> LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R nostd::details::__invoke_impl (__invoke_memfun_ref , _MemFun && __f, _Tp && __t, _Args &&... __args) inline
Definition at line 135 of file type_traits.h.
__invoke_impl() [3/5]
template<typename R , typename _MemPtr , typename _Tp > LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R nostd::details::__invoke_impl (__invoke_memobj_deref , _MemPtr && __f, _Tp && __t) inline
Definition at line 156 of file type_traits.h.
__invoke_impl() [4/5]
template<typename R , typename _MemPtr , typename _Tp > LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R nostd::details::__invoke_impl (__invoke_memobj_ref , _MemPtr && __f, _Tp && __t) inline
Definition at line 149 of file type_traits.h.
__invoke_impl() [5/5]
template<typename R , typename _Fn , typename... _Args> LIBCOPP_UTIL_SYMBOL_VISIBLE LIBCOPP_UTIL_NOSTD_INVOKE_RESULT_CONSTEXPR R nostd::details::__invoke_impl (__invoke_other , _Fn && __f, _Args &&... __args) inline
Definition at line 129 of file type_traits.h.
Referenced by __invoke().