libcopp: test_manager Class Reference
test_manager Class Reference
#include <test_manager.h>
Data Structures
struct convert_param
struct convert_param< TL, false >
struct convert_param< TL, true >
struct is_numberic
struct pick_param
struct pick_param< TL, TR, false, true, true >
struct pick_param< TL, TR, true, true, false >
struct try_convert_to_string_view
struct try_convert_to_string_view< const char *, CONVERTABLE_TO_SV >
struct try_convert_to_string_view< TVAL, false >
struct try_convert_to_string_view< TVAL, true >
Public Types
using case_ptr_type = test_case_base *
using on_start_ptr_type = test_on_start_base *
using on_exit_ptr_type = test_on_exit_base *
using test_type = std::vector< std::pair< std::string, case_ptr_type > >
using event_on_start_type = std::vector< std::pair< std::string, on_start_ptr_type > >
using event_on_exit_type = std::vector< std::pair< std::string, on_exit_ptr_type > >
using test_data_type = std::unordered_map< std::string, test_type >
using string_view_type = ::std::string
Public Member Functions
test_manager ()
virtual ~test_manager ()
void append_test_case (const std::string &test_name, const std::string &case_name, case_ptr_type)
void append_event_on_start (const std::string &event_name, on_start_ptr_type)
void append_event_on_exit (const std::string &event_name, on_exit_ptr_type)
int run_event_on_start ()
int run_event_on_exit ()
int run ()
void set_cases (const std::vector< std::string > &case_names)
template<class TL >
convert_param< TL >::type pick_convert_value (TL &&v)
template<class TL , class TR >
bool expect_eq (TL &&l, TR &&r, const char *lexpr, const char *rexpr, const char *file, size_t line)
template<class TL , class TR >
bool expect_ne (TL &&l, TR &&r, const char *lexpr, const char *rexpr, const char *file, size_t line)
template<class TL , class TR >
bool expect_lt (TL &&l, TR &&r, const char *lexpr, const char *rexpr, const char *file, size_t line)
template<class TL , class TR >
bool expect_le (TL &&l, TR &&r, const char *lexpr, const char *rexpr, const char *file, size_t line)
template<class TL , class TR >
bool expect_gt (TL &&l, TR &&r, const char *lexpr, const char *rexpr, const char *file, size_t line)
template<class TL , class TR >
bool expect_ge (TL &&l, TR &&r, const char *lexpr, const char *rexpr, const char *file, size_t line)
template<class TL >
bool expect_true (TL &&l, const char *expr, const char *file, size_t line)
template<class TL >
bool expect_false (TL &&l, const char *expr, const char *file, size_t line)
Static Public Member Functions
static test_manager & me ()
static std::string get_expire_time (clock_t begin, clock_t end)
static void set_counter_ptr (int *success_counter_ptr, int *failed_counter_ptr)
static void inc_success_counter ()
static void inc_failed_counter ()
Private Attributes
test_data_type tests_
event_on_start_type evt_on_starts_
event_on_exit_type evt_on_exits_
int success_
int failed_
std::unordered_set< std::string > run_cases_
std::unordered_set< std::string > run_groups_
Detailed Description
Definition at line 55 of file test_manager.h.
Member Typedef Documentation
case_ptr_type
using test_manager::case_ptr_type = test_case_base *
Definition at line 57 of file test_manager.h.
event_on_exit_type
using test_manager::event_on_exit_type = std::vector<std::pair<std::string, on_exit_ptr_type> >
Definition at line 62 of file test_manager.h.
event_on_start_type
using test_manager::event_on_start_type = std::vector<std::pair<std::string, on_start_ptr_type> >
Definition at line 61 of file test_manager.h.
on_exit_ptr_type
using test_manager::on_exit_ptr_type = test_on_exit_base *
Definition at line 59 of file test_manager.h.
on_start_ptr_type
using test_manager::on_start_ptr_type = test_on_start_base *
Definition at line 58 of file test_manager.h.
string_view_type
using test_manager::string_view_type = ::std::string
Definition at line 134 of file test_manager.h.
test_data_type
using test_manager::test_data_type = std::unordered_map<std::string, test_type>
Definition at line 63 of file test_manager.h.
test_type
using test_manager::test_type = std::vector<std::pair<std::string, case_ptr_type> >
Definition at line 60 of file test_manager.h.
Constructor & Destructor Documentation
test_manager()
test_manager::test_manager ()
Definition at line 109 of file test_manager.cpp.
References failed_, and success_.
~test_manager()
test_manager::~test_manager () virtual
Definition at line 114 of file test_manager.cpp.
Member Function Documentation
append_event_on_exit()
void test_manager::append_event_on_exit (const std::string & event_name, on_exit_ptr_type ptr)
Definition at line 124 of file test_manager.cpp.
References evt_on_exits_.
Referenced by test_on_exit_base::register_self().
append_event_on_start()
void test_manager::append_event_on_start (const std::string & event_name, on_start_ptr_type ptr)
Definition at line 120 of file test_manager.cpp.
References evt_on_starts_.
Referenced by test_on_start_base::register_self().
append_test_case()
void test_manager::append_test_case (const std::string & test_name, const std::string & case_name, case_ptr_type ptr)
Definition at line 116 of file test_manager.cpp.
References tests_.
Referenced by test_case_base::test_case_base().
expect_eq()
template<class TL , class TR > bool test_manager::expect_eq (TL && l, TR && r, const char * lexpr, const char * rexpr, const char * file, size_t line) inline
Definition at line 196 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_false()
template<class TL > bool test_manager::expect_false (TL && l, const char * expr, const char * file, size_t line) inline
Definition at line 325 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_ge()
template<class TL , class TR > bool test_manager::expect_ge (TL && l, TR && r, const char * lexpr, const char * rexpr, const char * file, size_t line) inline
Definition at line 290 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_gt()
template<class TL , class TR > bool test_manager::expect_gt (TL && l, TR && r, const char * lexpr, const char * rexpr, const char * file, size_t line) inline
Definition at line 271 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_le()
template<class TL , class TR > bool test_manager::expect_le (TL && l, TR && r, const char * lexpr, const char * rexpr, const char * file, size_t line) inline
Definition at line 252 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_lt()
template<class TL , class TR > bool test_manager::expect_lt (TL && l, TR && r, const char * lexpr, const char * rexpr, const char * file, size_t line) inline
Definition at line 233 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_ne()
template<class TL , class TR > bool test_manager::expect_ne (TL && l, TR && r, const char * lexpr, const char * rexpr, const char * file, size_t line) inline
Definition at line 214 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
expect_true()
template<class TL > bool test_manager::expect_true (TL && l, const char * expr, const char * file, size_t line) inline
Definition at line 309 of file test_manager.h.
References inc_failed_counter(), inc_success_counter(), pick_convert_value(), and util::cli::shell_font_style::SHELL_FONT_COLOR_RED.
get_expire_time()
std::string test_manager::get_expire_time (clock_t begin, clock_t end) static
Definition at line 397 of file test_manager.cpp.
Referenced by run().
inc_failed_counter()
void test_manager::inc_failed_counter () static
Definition at line 429 of file test_manager.cpp.
References detail::test_manager_tls_block_t::failed_counter_ptr, detail::get_test_manager_tls_block(), LIBCOPP_UTIL_LIKELY_CONDITION, util::cli::shell_font_style::SHELL_FONT_COLOR_RED, and util::cli::shell_font_style::SHELL_FONT_SPEC_BOLD.
Referenced by expect_eq(), expect_false(), expect_ge(), expect_gt(), expect_le(), expect_lt(), expect_ne(), and expect_true().
inc_success_counter()
void test_manager::inc_success_counter () static
Definition at line 416 of file test_manager.cpp.
References detail::get_test_manager_tls_block(), LIBCOPP_UTIL_LIKELY_CONDITION, util::cli::shell_font_style::SHELL_FONT_COLOR_RED, util::cli::shell_font_style::SHELL_FONT_SPEC_BOLD, and detail::test_manager_tls_block_t::success_counter_ptr.
Referenced by expect_eq(), expect_false(), expect_ge(), expect_gt(), expect_le(), expect_lt(), expect_ne(), and expect_true().
me()
test_manager & test_manager::me () static
Definition at line 392 of file test_manager.cpp.
Referenced by test_on_start_base::register_self(), test_on_exit_base::register_self(), run_event_on_exit(), run_event_on_start(), run_tests(), and test_case_base::test_case_base().
pick_convert_value()
template<class TL > convert_param< TL >::type test_manager::pick_convert_value (TL && v) inline
Definition at line 190 of file test_manager.h.
Referenced by expect_eq(), expect_false(), expect_ge(), expect_gt(), expect_le(), expect_lt(), expect_ne(), and expect_true().
run()
int test_manager::run ()
Definition at line 270 of file test_manager.cpp.
References failed_, get_expire_time(), run_cases_, run_groups_, util::cli::shell_font_style::SHELL_FONT_COLOR_GREEN, util::cli::shell_font_style::SHELL_FONT_COLOR_RED, util::cli::shell_font_style::SHELL_FONT_SPEC_BOLD, util::cli::shell_font_style::SHELL_FONT_SPEC_NULL, success_, and tests_.
Referenced by run_event_on_exit(), run_event_on_start(), and run_tests().
run_event_on_exit()
int test_manager::run_event_on_exit ()
Definition at line 224 of file test_manager.cpp.
References detail::topological_sort_object_t::dependency_count, evt_on_exits_, detail::topological_sort_object_t::name, detail::topological_sort_object_t::object, run(), util::cli::shell_font_style::SHELL_FONT_COLOR_GREEN, util::cli::shell_font_style::SHELL_FONT_SPEC_BOLD, util::cli::shell_font_style::SHELL_FONT_SPEC_NULL, and topological_sort().
Referenced by run_event_on_exit().
run_event_on_start()
int test_manager::run_event_on_start ()
Definition at line 179 of file test_manager.cpp.
References detail::topological_sort_object_t::dependency_count, evt_on_starts_, detail::topological_sort_object_t::name, detail::topological_sort_object_t::object, run(), util::cli::shell_font_style::SHELL_FONT_COLOR_GREEN, util::cli::shell_font_style::SHELL_FONT_SPEC_BOLD, util::cli::shell_font_style::SHELL_FONT_SPEC_NULL, and topological_sort().
Referenced by run_event_on_start().
set_cases()
void test_manager::set_cases (const std::vector< std::string > & case_names)
Definition at line 379 of file test_manager.cpp.
References run_cases_, and run_groups_.
Referenced by run_tests().
set_counter_ptr()
void test_manager::set_counter_ptr (int * success_counter_ptr, int * failed_counter_ptr) static
Definition at line 406 of file test_manager.cpp.
References detail::test_manager_tls_block_t::failed_counter_ptr, detail::g_global_counter_cache, detail::get_test_manager_tls_block(), and detail::test_manager_tls_block_t::success_counter_ptr.
Referenced by test_case_base::run().
Field Documentation
evt_on_exits_
event_on_exit_type test_manager::evt_on_exits_ private
Definition at line 347 of file test_manager.h.
Referenced by append_event_on_exit(), and run_event_on_exit().
evt_on_starts_
event_on_start_type test_manager::evt_on_starts_ private
Definition at line 346 of file test_manager.h.
Referenced by append_event_on_start(), and run_event_on_start().
failed_
int test_manager::failed_ private
Definition at line 349 of file test_manager.h.
Referenced by run(), and test_manager().
run_cases_
std::unordered_set<std::string> test_manager::run_cases_ private
Definition at line 350 of file test_manager.h.
Referenced by run(), and set_cases().
run_groups_
std::unordered_set<std::string> test_manager::run_groups_ private
Definition at line 351 of file test_manager.h.
Referenced by run(), and set_cases().
success_
int test_manager::success_ private
Definition at line 348 of file test_manager.h.
Referenced by run(), and test_manager().
tests_
test_data_type test_manager::tests_ private
Definition at line 345 of file test_manager.h.
Referenced by append_test_case(), and run().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/test/frame/test_manager.h
/home/runner/work/libcopp/libcopp/test/frame/test_manager.cpp