libcopp: util::string Namespace Reference
util::string Namespace Reference
Data Structures
struct int2str_helper
Functions
template<class TCH = char>
TCH tolower (TCH c)
字符转小写
template<class TCH = char>
TCH toupper (TCH c)
字符转大写
template<class TCH >
bool is_space (const TCH &c)
是否是空白字符
template<class TCH >
std::pair< const TCH *, size_t > trim (const TCH *str_begin, size_t sz, bool trim_left=true, bool trim_right=true)
移除两边或一边的空白字符
template<class TCH , class TCHE >
void reverse (TCH *begin, TCHE end_any)
翻转字符串
template<class TCH >
void reverse (TCH *begin, int end_any)
template<class TCH >
void reverse (TCH *begin, std::nullptr_t)
template<class T >
size_t int2str_unsigned (char *str, size_t strsz, T in)
template<class T >
size_t int2str_signed (char *str, size_t strsz, T in)
template<class T >
size_t int2str (char *str, size_t strsz, const T &in)
整数转字符串
template<class T , class TCHAR >
const TCHAR * str2int (T &out, const TCHAR *str, size_t strsz=0)
字符串转整数
template<class T , class TCHAR >
const TCHAR * str2int (T &out, const std::basic_string< TCHAR > &str)
template<class T , class TINPUT >
T to_int (TINPUT &&input)
字符串转整数
template<class TStr , class TCh >
void hex (TStr *out, TCh c, bool upper_case=false)
字符转十六进制表示
template<class TStr , class TCh >
void oct (TStr *out, TCh c)
字符转8进制表示
template<class TCh >
void serialization (const void *src, size_t ss, TCh *out, size_t &os)
字符转8进制表示
template<class Elem , class Traits >
void serialization (const void *src, size_t ss, std::basic_ostream< Elem, Traits > &out)
字符转8进制表示
template<class TCh >
void dumphex (const void *src, size_t ss, TCh *out, bool upper_case=false)
字符转16进制表示
template<class Elem , class Traits >
void dumphex (const void *src, size_t ss, std::basic_ostream< Elem, Traits > &out, bool upper_case=false)
字符转16进制表示
Function Documentation
dumphex() [1/2]
template<class Elem , class Traits > void util::string::dumphex (const void * src, size_t ss, std::basic_ostream< Elem, Traits > & out, bool upper_case = false)
字符转16进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出缓冲区
upper_case 是否大写
Definition at line 483 of file string_oprs.h.
dumphex() [2/2]
template<class TCh > void util::string::dumphex (const void * src, size_t ss, TCh * out, bool upper_case = false)
字符转16进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出buffer
upper_case 是否大写
Definition at line 467 of file string_oprs.h.
hex()
template<class TStr , class TCh > void util::string::hex (TStr * out, TCh c, bool upper_case = false)
字符转十六进制表示
Parameters
out 输出的字符串(缓冲区长度至少为2)
c 被转换的字符
upper_case 输出大写字符？
Definition at line 378 of file string_oprs.h.
int2str()
template<class T > size_t util::string::int2str (char * str, size_t strsz, const T & in) inline
整数转字符串
Parameters
str 输出的字符串缓冲区
strsz 字符串缓冲区长度
in 输入的数字
Returns
返回输出的数据长度，失败返回0
Definition at line 276 of file string_oprs.h.
int2str_signed()
template<class T > size_t util::string::int2str_signed (char * str, size_t strsz, T in)
Definition at line 240 of file string_oprs.h.
References int2str_unsigned().
Referenced by util::string::int2str_helper< T >::call().
int2str_unsigned()
template<class T > size_t util::string::int2str_unsigned (char * str, size_t strsz, T in)
Definition at line 213 of file string_oprs.h.
References reverse().
Referenced by util::string::int2str_helper< T >::call(), and int2str_signed().
is_space()
template<class TCH > bool util::string::is_space (const TCH & c) inline
是否是空白字符
Parameters
c 字符
Returns
如果是空白字符，返回true，否则返回false
Definition at line 121 of file string_oprs.h.
Referenced by str2int(), and trim().
oct()
template<class TStr , class TCh > void util::string::oct (TStr * out, TCh c)
字符转8进制表示
Parameters
out 输出的字符串(缓冲区长度至少为3)
c 被转换的字符
upper_case 输出大写字符？
Definition at line 405 of file string_oprs.h.
Referenced by serialization(), and serialization().
reverse() [1/3]
template<class TCH > void util::string::reverse (TCH * begin, int end_any) inline
Definition at line 203 of file string_oprs.h.
reverse() [2/3]
template<class TCH > void util::string::reverse (TCH * begin, std::nullptr_t) inline
Definition at line 208 of file string_oprs.h.
reverse() [3/3]
template<class TCH , class TCHE > void util::string::reverse (TCH * begin, TCHE end_any)
翻转字符串
Parameters
begin 字符串起始地址
end 字符串结束地址,填入NULL，则从begin开是找到\0结束
Definition at line 176 of file string_oprs.h.
References std::swap().
Referenced by int2str_unsigned().
serialization() [1/2]
template<class Elem , class Traits > void util::string::serialization (const void * src, size_t ss, std::basic_ostream< Elem, Traits > & out)
字符转8进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出缓冲区
Definition at line 445 of file string_oprs.h.
References oct().
serialization() [2/2]
template<class TCh > void util::string::serialization (const void * src, size_t ss, TCh * out, size_t & os)
字符转8进制表示
Parameters
src 输入的buffer
ss 输入的buffer长度
out 输出buffer
os 输出buffer长度，回传输出缓冲区使用的长度
Definition at line 419 of file string_oprs.h.
References oct().
str2int() [1/2]
template<class T , class TCHAR > const TCHAR * util::string::str2int (T & out, const std::basic_string< TCHAR > & str)
Definition at line 348 of file string_oprs.h.
References str2int().
str2int() [2/2]
template<class T , class TCHAR > const TCHAR * util::string::str2int (T & out, const TCHAR * str, size_t strsz = 0)
字符串转整数
Parameters
out 输出的整数
str 被转换的字符串
Note
性能肯定比sscanf系，和iostream系高。strtol系就不知道了
Definition at line 292 of file string_oprs.h.
References is_space(), and tolower().
Referenced by str2int(), and to_int().
to_int()
template<class T , class TINPUT > T util::string::to_int (TINPUT && input) inline
字符串转整数
Parameters
str 被转换的字符串
Returns
输出的整数
Definition at line 365 of file string_oprs.h.
References str2int().
tolower()
template<class TCH = char> TCH util::string::tolower (TCH c)
字符转小写
Parameters
c 字符
Returns
str 如果是大写字符输出响应的小写字符，否则原样返回
Note
用于替换标准函数里参数是int类型导致的某些编译器warning问题
Definition at line 92 of file string_oprs.h.
Referenced by str2int().
toupper()
template<class TCH = char> TCH util::string::toupper (TCH c)
字符转大写
Parameters
c 字符
Returns
str 如果是小写字符输出响应的大写字符，否则原样返回
Note
用于替换标准函数里参数是int类型导致的某些编译器warning问题
Definition at line 107 of file string_oprs.h.
trim()
template<class TCH > std::pair< const TCH *, size_t > util::string::trim (const TCH * str_begin, size_t sz, bool trim_left = true, bool trim_right = true)
移除两边或一边的空白字符
Parameters
str_begin 字符串起始地址
sz 字符串长度，填0则会自动判定长度
trim_left 是否移除左边的空白字符
trim_right 是否移除右边的空白字符
Returns
返回子串的起始地址和长度
Note
注意，返回的字符串是源的子串，共享地址。并且不保证以0结尾，需要用返回的长度来判定子串长度
Definition at line 135 of file string_oprs.h.
References is_space().