libcopp: /home/runner/work/libcopp/libcopp/test/frame/test_manager.h File Reference
test_manager.h File Reference
#include <stdint.h>
#include <ctime>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include "cli/shell_font.h"
#include "test_case_base.h"
#include <map>
#include <set>
Data Structures
class test_manager
struct test_manager::is_numberic< T >
struct test_manager::pick_param< TL, TR, true, true, false >
struct test_manager::pick_param< TL, TR, false, true, true >
struct test_manager::try_convert_to_string_view< TVAL, true >
struct test_manager::try_convert_to_string_view< const char *, CONVERTABLE_TO_SV >
struct test_manager::try_convert_to_string_view< TVAL, false >
struct test_manager::pick_param< TL, TR, has_pointer, has_integer, all_integer >
struct test_manager::convert_param< TL, true >
struct test_manager::convert_param< TL, false >
Macros
#define UTILS_TEST_ENV_AUTO_MAP(...) std::map<__VA_ARGS__>
#define UTILS_TEST_ENV_AUTO_SET(...) std::set<__VA_ARGS__>
Functions
int run_event_on_start ()
int run_event_on_exit ()
int run_tests (int argc, char *argv[])
Macro Definition Documentation
UTILS_TEST_ENV_AUTO_MAP
#define UTILS_TEST_ENV_AUTO_MAP (...) std::map<__VA_ARGS__>
Definition at line 47 of file test_manager.h.
UTILS_TEST_ENV_AUTO_SET
#define UTILS_TEST_ENV_AUTO_SET (...) std::set<__VA_ARGS__>
Definition at line 48 of file test_manager.h.
Function Documentation
run_event_on_exit()
int run_event_on_exit ()
Definition at line 444 of file test_manager.cpp.
References test_manager::me(), and test_manager::run_event_on_exit().
Referenced by main(), and run_tests().
run_event_on_start()
int run_event_on_start ()
Definition at line 442 of file test_manager.cpp.
References test_manager::me(), and test_manager::run_event_on_start().
Referenced by main(), and run_tests().
run_tests()
int run_tests (int argc, char * argv[])
Definition at line 446 of file test_manager.cpp.
References util::cli::cmd_option_bind< TCmdStr >::create(), test_manager::me(), util::cli::phoenix::push_back(), test_manager::run(), run_event_on_exit(), run_event_on_start(), test_manager::set_cases(), and util::cli::phoenix::set_const().
Referenced by main().