libcopp: test_this_context_get_cotoutine_runner Class Reference
test_this_context_get_cotoutine_runner Class Reference
Public Types
typedef copp::coroutine_context_default value_type
typedef value_type * value_ptr_type
Public Member Functions
test_this_context_get_cotoutine_runner ()
int operator() (void *passed)
void set_co_obj (value_ptr_type addr)
bool is_run ()
Static Public Member Functions
static int get_max_thd_count ()
Private Attributes
value_ptr_type addr_
bool run_
Static Private Attributes
static std::atomic_int cur_thd_count
static int max_thd_count = 0
Detailed Description
Definition at line 21 of file coroutine_context_this_coroutine_test.cpp.
Member Typedef Documentation
value_ptr_type
typedef value_type* test_this_context_get_cotoutine_runner::value_ptr_type
Definition at line 24 of file coroutine_context_this_coroutine_test.cpp.
value_type
typedef copp::coroutine_context_default test_this_context_get_cotoutine_runner::value_type
Definition at line 23 of file coroutine_context_this_coroutine_test.cpp.
Constructor & Destructor Documentation
test_this_context_get_cotoutine_runner()
test_this_context_get_cotoutine_runner::test_this_context_get_cotoutine_runner () inline
Definition at line 27 of file coroutine_context_this_coroutine_test.cpp.
Member Function Documentation
get_max_thd_count()
static int test_this_context_get_cotoutine_runner::get_max_thd_count () inline static
Definition at line 53 of file coroutine_context_this_coroutine_test.cpp.
References max_thd_count.
Referenced by CASE_TEST().
is_run()
bool test_this_context_get_cotoutine_runner::is_run () inline
Definition at line 51 of file coroutine_context_this_coroutine_test.cpp.
References run_.
Referenced by test_this_context_thread_func().
operator()()
int test_this_context_get_cotoutine_runner::operator() (void * passed) inline
Definition at line 28 of file coroutine_context_this_coroutine_test.cpp.
References addr_, CASE_EXPECT_EQ, cur_thd_count, this_coroutine::get_coroutine(), this_task::get_task(), max_thd_count, and run_.
set_co_obj()
void test_this_context_get_cotoutine_runner::set_co_obj (value_ptr_type addr) inline
Definition at line 50 of file coroutine_context_this_coroutine_test.cpp.
References addr_.
Referenced by test_this_context_thread_func().
Field Documentation
addr_
value_ptr_type test_this_context_get_cotoutine_runner::addr_ private
Definition at line 56 of file coroutine_context_this_coroutine_test.cpp.
Referenced by operator()(), and set_co_obj().
cur_thd_count
std::atomic_int test_this_context_get_cotoutine_runner::cur_thd_count static private
Definition at line 58 of file coroutine_context_this_coroutine_test.cpp.
Referenced by operator()().
max_thd_count
int test_this_context_get_cotoutine_runner::max_thd_count = 0 static private
Definition at line 59 of file coroutine_context_this_coroutine_test.cpp.
Referenced by get_max_thd_count(), and operator()().
run_
bool test_this_context_get_cotoutine_runner::run_ private
Definition at line 57 of file coroutine_context_this_coroutine_test.cpp.
Referenced by is_run(), and operator()().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/test/case/coroutine_context_this_coroutine_test.cpp