libcopp: std Namespace Reference
std Namespace Reference
STL namespace.
Data Structures
class allocator
STL class.
class array
STL class.
class atomic
STL class.
class atomic_ref
STL class.
class auto_ptr
STL class.
class bad_alloc
STL class.
class bad_cast
STL class.
class bad_exception
STL class.
class bad_typeid
STL class.
class basic_fstream
STL class.
class basic_ifstream
STL class.
class basic_ios
STL class.
class basic_iostream
STL class.
class basic_istream
STL class.
class basic_istringstream
STL class.
class basic_ofstream
STL class.
class basic_ostream
STL class.
class basic_ostringstream
STL class.
class basic_string
STL class.
class basic_string_view
STL class.
class basic_stringstream
STL class.
class bitset
STL class.
class complex
STL class.
class deque
STL class.
class domain_error
STL class.
class error_category
STL class.
class error_code
STL class.
class error_condition
STL class.
class exception
STL class.
class forward_list
STL class.
class fstream
STL class.
struct hash< LIBCOPP_COPP_NAMESPACE_ID::gsl::not_null< T > >
struct hash< LIBCOPP_COPP_NAMESPACE_ID::gsl::strict_not_null< T > >
struct hash< LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > >
Support std::hash for strong_rc_ptr.
class ifstream
STL class.
class invalid_argument
STL class.
class ios
STL class.
class ios_base
STL class.
class istream
STL class.
class istringstream
STL class.
class jthread
STL class.
class length_error
STL class.
class list
STL class.
class lock_guard
STL class.
class logic_error
STL class.
class map
STL class.
class multimap
STL class.
class multiset
STL class.
class mutex
STL class.
class ofstream
STL class.
class ostream
STL class.
class ostringstream
STL class.
class out_of_range
STL class.
class overflow_error
STL class.
class priority_queue
STL class.
class queue
STL class.
class range_error
STL class.
class recursive_mutex
STL class.
class recursive_timed_mutex
STL class.
class runtime_error
STL class.
class set
STL class.
class shared_lock
STL class.
class shared_mutex
STL class.
class shared_ptr
STL class.
class shared_timed_mutex
STL class.
class smart_ptr
STL class.
class span
STL class.
class stack
STL class.
class string
STL class.
class string_view
STL class.
class stringstream
STL class.
class system_error
STL class.
class thread
STL class.
class timed_mutex
STL class.
class u16string
STL class.
class u16string_view
STL class.
class u32string
STL class.
class u32string_view
STL class.
class u8string
STL class.
class u8string_view
STL class.
class underflow_error
STL class.
class unique_lock
STL class.
class unique_ptr
STL class.
class unordered_map
STL class.
class unordered_multimap
STL class.
class unordered_multiset
STL class.
class unordered_set
STL class.
class valarray
STL class.
class vector
STL class.
class weak_ptr
STL class.
class wfstream
STL class.
class wifstream
STL class.
class wios
STL class.
class wistream
STL class.
class wistringstream
STL class.
class wofstream
STL class.
class wostream
STL class.
class wostringstream
STL class.
class wstring
STL class.
class wstring_view
STL class.
class wstringstream
STL class.
Functions
template<class T >
ostream & operator<< (ostream &os, const LIBCOPP_COPP_NAMESPACE_ID::gsl::not_null< T > &val)
template<class T >
LIBCOPP_COPP_API_HEAD_ONLY void swap (LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > &a, LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > &b) noexcept
Support std::swap for strong_rc_ptr.
template<class CharT , class TraitT , class T >
LIBCOPP_COPP_API_HEAD_ONLY std::basic_ostream< CharT, TraitT > & operator<< (std::basic_ostream< CharT, TraitT > &__os, const LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > &__p)
Support std::basic_ostream for strong_rc_ptr.
Detailed Description
STL namespace.
导入引用包装（std::ref, std::cref, std::reference_wrapper） 如果是G++且支持c++0x草案1（tr1版本）的smart_ptr[GCC版本高于4.0] 则会启用GNU-C++的引用包装
如果是VC++且支持c++0x草案1（tr1版本）的smart_ptr[VC++版本高于9.0 SP1] 则会启用VC++的引用包装
否则启用boost中的引用包装库（如果是这种情况需要加入boost库）
导入多维元组（tuple） 相当于std::pair的增强版，最多支持10维 如果是G++且支持c++0x草案1（tr1版本）的tuple[GCC版本高于4.0] 则会启用GNU-C++的多维元组
如果是VC++且支持c++0x草案1（tr1版本）的tuple[VC++版本高于9.0 SP1] 则会启用VC++的多维元组
否则启用boost中的tuple库（如果是这种情况需要加入boost库）
导入utility文件（utility） 如果是G++且支持c++0x草案1（tr1版本）的utility[GCC版本高于4.0] 则会启用GNU-C++的utility
如果是VC++且支持c++0x草案1（tr1版本）的utility[VC++版本高于9.0 SP1] 则会启用VC++的utility
否则启用boost中的utility库（如果是这种情况需要加入boost库）
Function Documentation
operator<<() [1/2]
template<class T > ostream & std::operator<< (ostream & os, const LIBCOPP_COPP_NAMESPACE_ID::gsl::not_null< T > & val)
Definition at line 258 of file not_null.h.
operator<<() [2/2]
template<class CharT , class TraitT , class T > LIBCOPP_COPP_API_HEAD_ONLY std::basic_ostream< CharT, TraitT > & std::operator<< (std::basic_ostream< CharT, TraitT > & __os, const LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > & __p) inline private
Support std::basic_ostream for strong_rc_ptr.
Parameters
a A strong_rc_ptr instance.
b Another strong_rc_ptr instance.
Definition at line 1400 of file rc_ptr.h.
swap()
template<class T > LIBCOPP_COPP_API_HEAD_ONLY void std::swap (LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > & a, LIBCOPP_COPP_NAMESPACE_ID::memory::strong_rc_ptr< T > & b) private noexcept
Support std::swap for strong_rc_ptr.
Parameters
a A strong_rc_ptr instance.
b Another strong_rc_ptr instance.
Definition at line 1377 of file rc_ptr.h.
Referenced by util::string::reverse(), coroutine_context::start(), future::result_base< TOK, TERR, true >::swap(), future::result_base< TOK, TERR, false >::swap(), allocator::stack_allocator_memory::swap(), future::poll_storage_base< T, TPTR >::swap(), memory::strong_rc_ptr< T >::swap(), memory::weak_rc_ptr< T >::swap(), strong_rc::n_swap::test(), and weak_rc::n_swap::test().