libcopp: stack_traits Struct Reference
stack_traits Struct Reference
#include <stack_traits.h>
Static Public Member Functions
static LIBCOPP_COPP_API bool is_unbounded () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t page_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t default_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t minimum_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t maximum_size () LIBCOPP_MACRO_NOEXCEPT
static LIBCOPP_COPP_API std::size_t round_to_page_size (std::size_t stacksize) LIBCOPP_MACRO_NOEXCEPT
Detailed Description
Definition at line 23 of file stack_traits.h.
Member Function Documentation
default_size()
LIBCOPP_COPP_API std::size_t stack_traits::default_size () static
Definition at line 65 of file stack_traits_posix.cpp.
References is_unbounded(), maximum_size(), and minimum_size().
Referenced by coroutine_context_container< TALLOC >::create().
is_unbounded()
LIBCOPP_COPP_API bool stack_traits::is_unbounded () static
Definition at line 59 of file stack_traits_posix.cpp.
References detail::stacksize_limit().
Referenced by allocator::stack_allocator_windows::allocate(), allocator::stack_allocator_posix::deallocate(), allocator::stack_allocator_windows::deallocate(), allocator::stack_allocator_malloc::deallocate(), allocator::stack_allocator_memory::deallocate(), default_size(), and maximum_size().
maximum_size()
LIBCOPP_COPP_API std::size_t stack_traits::maximum_size () static
Definition at line 77 of file stack_traits_posix.cpp.
References is_unbounded(), and detail::stacksize_limit().
Referenced by allocator::stack_allocator_posix::allocate(), allocator::stack_allocator_windows::allocate(), allocator::stack_allocator_malloc::allocate(), allocator::stack_allocator_memory::allocate(), allocator::stack_allocator_posix::deallocate(), allocator::stack_allocator_windows::deallocate(), allocator::stack_allocator_malloc::deallocate(), allocator::stack_allocator_memory::deallocate(), and default_size().
minimum_size()
LIBCOPP_COPP_API std::size_t stack_traits::minimum_size () static
Definition at line 73 of file stack_traits_posix.cpp.
References MINSIGSTKSZ.
Referenced by allocator::stack_allocator_posix::allocate(), allocator::stack_allocator_windows::allocate(), allocator::stack_allocator_malloc::allocate(), allocator::stack_allocator_memory::allocate(), allocator::stack_allocator_posix::deallocate(), allocator::stack_allocator_windows::deallocate(), allocator::stack_allocator_malloc::deallocate(), allocator::stack_allocator_memory::deallocate(), and default_size().
page_size()
LIBCOPP_COPP_API std::size_t stack_traits::page_size () static
Definition at line 63 of file stack_traits_posix.cpp.
References detail::pagesize().
Referenced by allocator::stack_allocator_posix::allocate(), and allocator::stack_allocator_windows::allocate().
round_to_page_size()
LIBCOPP_COPP_API std::size_t stack_traits::round_to_page_size (std::size_t stacksize) static
Definition at line 82 of file stack_traits_posix.cpp.
References detail::pagesize().
Referenced by allocator::stack_allocator_posix::allocate(), allocator::stack_allocator_windows::allocate(), allocator::stack_allocator_malloc::allocate(), and allocator::stack_allocator_memory::allocate().
The documentation for this struct was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcopp/stack/stack_traits.h
/home/runner/work/libcopp/libcopp/src/libcopp/stack/stack_traits/stack_traits_posix.cpp
/home/runner/work/libcopp/libcopp/src/libcopp/stack/stack_traits/stack_traits_windows.cpp