libcopp: /home/runner/work/libcopp/libcopp/test/app/main.cpp File Reference
main.cpp File Reference
#include "frame/test_macros.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 33 of file main.cpp.
References run_event_on_exit(), run_event_on_start(), and run_tests().