libcopp: impl::task_impl Class Reference
impl::task_impl Class Reference abstract
#include <task_impl.h>
Data Structures
struct ext_coroutine_flag_t
Public Types
using id_type = LIBCOPP_COPP_NAMESPACE_ID::util::uint64_id_allocator::value_type
using id_allocator_type = LIBCOPP_COPP_NAMESPACE_ID::util::uint64_id_allocator
using id_t = id_type
using id_allocator_t = id_allocator_type
Public Member Functions
LIBCOPP_COTASK_API task_impl ()
virtual LIBCOPP_COTASK_API ~task_impl ()=0
LIBCOPP_UTIL_FORCEINLINE id_type get_id () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_UTIL_FORCEINLINE EN_TASK_STATUS get_status () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_canceled () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_completed () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_faulted () const LIBCOPP_MACRO_NOEXCEPT
virtual LIBCOPP_COTASK_API bool is_timeout () const LIBCOPP_MACRO_NOEXCEPT
LIBCOPP_COTASK_API bool is_exiting () const LIBCOPP_MACRO_NOEXCEPT
check if a cotask is exiting
virtual LIBCOPP_COTASK_API int get_ret_code () const =0
virtual int start (void *priv_data, EN_TASK_STATUS expected_status=EN_TS_CREATED)=0
virtual int resume (void *priv_data, EN_TASK_STATUS expected_status=EN_TS_WAITING)=0
virtual int yield (void **priv_data)=0
virtual int cancel (void *priv_data)=0
virtual int kill (enum EN_TASK_STATUS status, void *priv_data)=0
LIBCOPP_UTIL_FORCEINLINE int kill (void *priv_data)
LIBCOPP_UTIL_FORCEINLINE int start ()
LIBCOPP_UTIL_FORCEINLINE int resume ()
LIBCOPP_UTIL_FORCEINLINE int yield ()
LIBCOPP_UTIL_FORCEINLINE int cancel ()
LIBCOPP_UTIL_FORCEINLINE int kill (enum EN_TASK_STATUS status)
LIBCOPP_UTIL_FORCEINLINE int kill ()
virtual LIBCOPP_COTASK_API int on_finished ()
LIBCOPP_UTIL_FORCEINLINE action_ptr_type get_raw_action () const LIBCOPP_MACRO_NOEXCEPT
get raw action pointer
Static Public Member Functions
static LIBCOPP_COTASK_API task_impl * this_task ()
Protected Types
using action_ptr_type = task_action_impl *
using action_ptr_t = action_ptr_type
Protected Member Functions
LIBCOPP_COTASK_API void _set_action (action_ptr_type action)
LIBCOPP_COTASK_API action_ptr_type _get_action ()
LIBCOPP_COTASK_API bool _cas_status (EN_TASK_STATUS &expected, EN_TASK_STATUS desired)
LIBCOPP_COTASK_API int _notify_finished (void *priv_data)
Protected Attributes
void * finish_priv_data_
Private Member Functions
task_impl (const task_impl &)=delete
task_impl & operator= (const task_impl &)=delete
task_impl (const task_impl &&)=delete
task_impl & operator= (const task_impl &&)=delete
Private Attributes
action_ptr_type action_
id_type id_
LIBCOPP_COPP_NAMESPACE_ID::util::lock::atomic_int_type< LIBCOPP_COPP_NAMESPACE_ID::util::lock::unsafe_int_type< uint32_t > > status_
Detailed Description
Definition at line 42 of file task_impl.h.
Member Typedef Documentation
action_ptr_t
using impl::task_impl::action_ptr_t = action_ptr_type protected
Definition at line 55 of file task_impl.h.
action_ptr_type
using impl::task_impl::action_ptr_type = task_action_impl * protected
Definition at line 52 of file task_impl.h.
id_allocator_t
using impl::task_impl::id_allocator_t = id_allocator_type
Definition at line 49 of file task_impl.h.
id_allocator_type
using impl::task_impl::id_allocator_type = LIBCOPP_COPP_NAMESPACE_ID::util::uint64_id_allocator
Definition at line 45 of file task_impl.h.
id_t
using impl::task_impl::id_t = id_type
Definition at line 48 of file task_impl.h.
id_type
using impl::task_impl::id_type = LIBCOPP_COPP_NAMESPACE_ID::util::uint64_id_allocator::value_type
Definition at line 44 of file task_impl.h.
Constructor & Destructor Documentation
task_impl() [1/3]
impl::task_impl::task_impl (const task_impl &) private delete
task_impl() [2/3]
impl::task_impl::task_impl (const task_impl &&) private delete
task_impl() [3/3]
LIBCOPP_COTASK_API impl::task_impl::task_impl ()
Definition at line 23 of file task_impl.cpp.
References id_.
~task_impl()
LIBCOPP_COTASK_API impl::task_impl::~task_impl () pure virtual
Definition at line 30 of file task_impl.cpp.
References EN_TS_DONE, and id_.
Member Function Documentation
_cas_status()
LIBCOPP_COTASK_API bool impl::task_impl::_cas_status (EN_TASK_STATUS & expected, EN_TASK_STATUS desired) protected
Definition at line 69 of file task_impl.cpp.
References status_.
Referenced by task< TCO_MACRO >::cancel(), task< TCO_MACRO >::kill(), and task< TCO_MACRO >::start().
_get_action()
LIBCOPP_COTASK_API task_impl::action_ptr_type impl::task_impl::_get_action () protected
Definition at line 67 of file task_impl.cpp.
References action_.
Referenced by _notify_finished(), and task< TCO_MACRO >::~task().
_notify_finished()
LIBCOPP_COTASK_API int impl::task_impl::_notify_finished (void * priv_data) protected
Definition at line 81 of file task_impl.cpp.
References _get_action(), finish_priv_data_, on_finished(), and impl::task_action_impl::on_finished().
Referenced by task< TCO_MACRO >::_notify_finished(), task< TCO_MACRO >::cancel(), task< TCO_MACRO >::kill(), and task< TCO_MACRO >::start().
_set_action()
LIBCOPP_COTASK_API void impl::task_impl::_set_action (action_ptr_type action) protected
Definition at line 65 of file task_impl.cpp.
References action_.
Referenced by task< TCO_MACRO >::~task().
cancel() [1/2]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::cancel () inline
Definition at line 112 of file task_impl.h.
References cancel().
Referenced by cancel().
cancel() [2/2]
virtual int impl::task_impl::cancel (void * priv_data) pure virtual
Implemented in task< TCO_MACRO >, and task< TCO_MACRO >.
get_id()
LIBCOPP_UTIL_FORCEINLINE id_type impl::task_impl::get_id () const inline
Definition at line 76 of file task_impl.h.
Referenced by task_manager< task< TCO_MACRO > >::add_task(), and main().
get_raw_action()
LIBCOPP_UTIL_FORCEINLINE action_ptr_type impl::task_impl::get_raw_action () const inline
get raw action pointer
Note
this function is provided just for debug or show some information, it may return the inner type created by cotask
Returns
pointer to task_action instance
Definition at line 134 of file task_impl.h.
get_ret_code()
virtual LIBCOPP_COTASK_API int impl::task_impl::get_ret_code () const pure virtual
Implemented in task< TCO_MACRO >, and task< TCO_MACRO >.
get_status()
LIBCOPP_UTIL_FORCEINLINE EN_TASK_STATUS impl::task_impl::get_status () const inline
get task status
Returns
task status
Definition at line 82 of file task_impl.h.
Referenced by task< TCO_MACRO >::cancel(), is_canceled(), is_exiting(), is_faulted(), is_timeout(), task< TCO_MACRO >::kill(), and task< TCO_MACRO >::~task().
is_canceled()
LIBCOPP_COTASK_API bool impl::task_impl::is_canceled () const virtual
Definition at line 39 of file task_impl.cpp.
References EN_TS_CANCELED, and get_status().
is_completed()
LIBCOPP_COTASK_API bool impl::task_impl::is_completed () const virtual
Reimplemented in task< TCO_MACRO >, and task< TCO_MACRO >.
Definition at line 41 of file task_impl.cpp.
References is_exiting().
Referenced by task< TCO_MACRO >::next(), and task< TCO_MACRO >::start().
is_exiting()
LIBCOPP_COTASK_API bool impl::task_impl::is_exiting () const
check if a cotask is exiting
Note
cotask is exiting means the cotask is is_completed() or is killed. if a cotask is killed and is running, then is_completed() == false but is_exiting() == true, and after the cotask finished, is_completed() == true
Returns
return true if a cotask is exiting.
Definition at line 47 of file task_impl.cpp.
References EN_TS_DONE, and get_status().
Referenced by task_manager< task< TCO_MACRO > >::add_task(), task< TCO_MACRO >::await_task(), is_completed(), and task< TCO_MACRO >::next().
is_faulted()
LIBCOPP_COTASK_API bool impl::task_impl::is_faulted () const virtual
Definition at line 43 of file task_impl.cpp.
References EN_TS_KILLED, and get_status().
is_timeout()
LIBCOPP_COTASK_API bool impl::task_impl::is_timeout () const virtual
Definition at line 45 of file task_impl.cpp.
References EN_TS_TIMEOUT, and get_status().
kill() [1/4]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::kill () inline
Definition at line 114 of file task_impl.h.
References kill().
Referenced by kill(), and task< TCO_MACRO >::~task().
kill() [2/4]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::kill (enum EN_TASK_STATUS status) inline
Definition at line 113 of file task_impl.h.
References kill().
Referenced by kill().
kill() [3/4]
virtual int impl::task_impl::kill (enum EN_TASK_STATUS status, void * priv_data) pure virtual
Implemented in task< TCO_MACRO >, and task< TCO_MACRO >.
kill() [4/4]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::kill (void * priv_data) inline
Definition at line 107 of file task_impl.h.
References EN_TS_KILLED, and kill().
Referenced by kill().
on_finished()
LIBCOPP_COTASK_API int impl::task_impl::on_finished () virtual
Definition at line 49 of file task_impl.cpp.
Referenced by _notify_finished().
operator=() [1/2]
task_impl & impl::task_impl::operator= (const task_impl &&) private delete
operator=() [2/2]
task_impl & impl::task_impl::operator= (const task_impl &) private delete
resume() [1/2]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::resume () inline
Definition at line 110 of file task_impl.h.
References resume().
Referenced by resume().
resume() [2/2]
virtual int impl::task_impl::resume (void * priv_data, EN_TASK_STATUS expected_status = EN_TS_WAITING) pure virtual
Implemented in task< TCO_MACRO >, and task< TCO_MACRO >.
start() [1/2]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::start () inline
Definition at line 109 of file task_impl.h.
References start().
Referenced by task< TCO_MACRO >::resume(), and start().
start() [2/2]
virtual int impl::task_impl::start (void * priv_data, EN_TASK_STATUS expected_status = EN_TS_CREATED) pure virtual
Implemented in task< TCO_MACRO >, and task< TCO_MACRO >.
this_task()
LIBCOPP_COTASK_API task_impl * impl::task_impl::this_task () static
get current running task
Returns
current running task or empty pointer
Definition at line 51 of file task_impl.cpp.
References impl::task_impl::ext_coroutine_flag_t::EN_ECFT_COTASK.
Referenced by task< TCO_MACRO >::await_task(), this_task::get_task(), and task< TCO_MACRO >::this_task().
yield() [1/2]
LIBCOPP_UTIL_FORCEINLINE int impl::task_impl::yield () inline
Definition at line 111 of file task_impl.h.
References yield().
Referenced by task< TCO_MACRO >::await_task(), and yield().
yield() [2/2]
virtual int impl::task_impl::yield (void ** priv_data) pure virtual
Implemented in task< TCO_MACRO >, and task< TCO_MACRO >.
Field Documentation
action_
action_ptr_type impl::task_impl::action_ private
Definition at line 149 of file task_impl.h.
Referenced by _get_action(), and _set_action().
finish_priv_data_
void* impl::task_impl::finish_priv_data_ protected
Definition at line 153 of file task_impl.h.
Referenced by _notify_finished().
id_
id_type impl::task_impl::id_ private
Definition at line 150 of file task_impl.h.
Referenced by task_impl(), and ~task_impl().
status_
LIBCOPP_COPP_NAMESPACE_ID::util::lock::atomic_int_type< LIBCOPP_COPP_NAMESPACE_ID::util::lock::unsafe_int_type<uint32_t> > impl::task_impl::status_ private
Definition at line 161 of file task_impl.h.
Referenced by _cas_status().
The documentation for this class was generated from the following files:
/home/runner/work/libcopp/libcopp/include/libcotask/impl/task_impl.h
/home/runner/work/libcopp/libcopp/src/libcotask/impl/task_impl.cpp