libcopp: strong_rc::n_spt_abstract Namespace Reference
strong_rc::n_spt_abstract Namespace Reference
Data Structures
class X
class X_impl
Functions
copp::memory::strong_rc_ptr< X > createX ()
void test ()
Variables
int X_instances = 0
Function Documentation
createX()
copp::memory::strong_rc_ptr< X > strong_rc::n_spt_abstract::createX ()
Definition at line 2619 of file rc_ptr_test.cpp.
Referenced by test().
test()
void strong_rc::n_spt_abstract::test ()
Definition at line 2201 of file rc_ptr_test.cpp.
References CASE_EXPECT_TRUE, createX(), and X_instances.
Referenced by strong_rc::CASE_TEST().
Variable Documentation
X_instances
int strong_rc::n_spt_abstract::X_instances = 0
Definition at line 2199 of file rc_ptr_test.cpp.
Referenced by test(), strong_rc::n_spt_abstract::X_impl::X_impl(), and strong_rc::n_spt_abstract::X_impl::~X_impl().