libcopp: strong_rc::n_spt_another_sp Namespace Reference
strong_rc::n_spt_another_sp Namespace Reference
Data Structures
class another_ptr
class event_handler
class event_handler_impl
class smart_pointer_deleter
Functions
another_ptr< event_handler > get_event_handler ()
void install_event_handler (copp::memory::strong_rc_ptr< event_handler > p)
void handle_event (int event)
void remove_event_handler ()
void test ()
Variables
int begin_called = 0
int handle_called = 0
int end_called = 0
copp::memory::strong_rc_ptr< event_handler > current_handler
Function Documentation
get_event_handler()
another_ptr< event_handler > strong_rc::n_spt_another_sp::get_event_handler ()
Definition at line 2392 of file rc_ptr_test.cpp.
Referenced by test().
handle_event()
void strong_rc::n_spt_another_sp::handle_event (int event)
Definition at line 2404 of file rc_ptr_test.cpp.
References current_handler.
Referenced by test().
install_event_handler()
void strong_rc::n_spt_another_sp::install_event_handler (copp::memory::strong_rc_ptr< event_handler > p)
Definition at line 2399 of file rc_ptr_test.cpp.
References current_handler.
Referenced by test().
remove_event_handler()
void strong_rc::n_spt_another_sp::remove_event_handler ()
Definition at line 2406 of file rc_ptr_test.cpp.
References current_handler, and strong_rc::n_spt_another_sp::another_ptr< T >::reset().
Referenced by test().
test()
void strong_rc::n_spt_another_sp::test ()
Definition at line 2422 of file rc_ptr_test.cpp.
References begin_called, CASE_EXPECT_TRUE, end_called, strong_rc::n_spt_another_sp::another_ptr< T >::get(), get_event_handler(), handle_called, handle_event(), install_event_handler(), remove_event_handler(), and strong_rc::n_spt_another_sp::another_ptr< T >::reset().
Referenced by strong_rc::CASE_TEST().
Variable Documentation
begin_called
int strong_rc::n_spt_another_sp::begin_called = 0
Definition at line 2379 of file rc_ptr_test.cpp.
Referenced by strong_rc::n_spt_another_sp::event_handler_impl::begin(), and test().
current_handler
copp::memory::strong_rc_ptr<event_handler> strong_rc::n_spt_another_sp::current_handler
Definition at line 2397 of file rc_ptr_test.cpp.
Referenced by handle_event(), install_event_handler(), and remove_event_handler().
end_called
int strong_rc::n_spt_another_sp::end_called = 0
Definition at line 2381 of file rc_ptr_test.cpp.
Referenced by strong_rc::n_spt_another_sp::event_handler_impl::end(), and test().
handle_called
int strong_rc::n_spt_another_sp::handle_called = 0
Definition at line 2380 of file rc_ptr_test.cpp.
Referenced by strong_rc::n_spt_another_sp::event_handler_impl::handle(), and test().