libcopp: print_color Namespace Reference
print_color Namespace Reference
Data Structures
class HtmlColor
class NoneColor
class print_style
class TermColor
class Win32ConsoleColor
Functions
cprintf_resolve_auto_mode ()
cprintf_set_mode (mode_name="auto")
cprintf_set_theme (theme_name=None)
cprintf_unpack_text (fmt, text)
cprintf_stdout (options, fmt, *text)
cprintf_stderr (options, fmt, *text)
Variables
console_encoding = sys.getfilesystemencoding()
str usage = "usage: %prog [options...] <format message> [format parameters...]"
parser = OptionParser(usage)
action
help
dest
metavar
const
default
options
left_args
str print_stream = "stdout"
list print_options = []
list fc_list = ["FC_" + x.upper() for x in options.color or []]
list bk_list = ["BC_" + y.upper() for y in options.background_color or []]
Function Documentation
cprintf_resolve_auto_mode()
print_color.cprintf_resolve_auto_mode ()
Definition at line 238 of file print_color.py.
Referenced by cprintf_set_mode().
cprintf_set_mode()
print_color.cprintf_set_mode (mode_name = "auto")
Definition at line 284 of file print_color.py.
References cprintf_resolve_auto_mode(), and cprintf_set_mode().
Referenced by cprintf_set_mode(), and cprintf_stderr().
cprintf_set_theme()
print_color.cprintf_set_theme (theme_name = None)
Definition at line 314 of file print_color.py.
References cprintf_set_theme().
Referenced by cprintf_set_theme().
cprintf_stderr()
print_color.cprintf_stderr (options, fmt, * text)
Definition at line 343 of file print_color.py.
References cprintf_set_mode(), and cprintf_unpack_text().
cprintf_stdout()
print_color.cprintf_stdout (options, fmt, * text)
Definition at line 337 of file print_color.py.
References cprintf_unpack_text().
cprintf_unpack_text()
print_color.cprintf_unpack_text (fmt, text)
Definition at line 322 of file print_color.py.
Referenced by cprintf_stderr(), and cprintf_stdout().
Variable Documentation
action
print_color.action
Definition at line 361 of file print_color.py.
bk_list
list print_color.bk_list = ["BC_" + y.upper() for y in options.background_color or []]
Definition at line 439 of file print_color.py.
console_encoding
print_color.console_encoding = sys.getfilesystemencoding()
Definition at line 10 of file print_color.py.
const
print_color.const
Definition at line 388 of file print_color.py.
default
print_color.default
Definition at line 406 of file print_color.py.
dest
print_color.dest
Definition at line 363 of file print_color.py.
fc_list
list print_color.fc_list = ["FC_" + x.upper() for x in options.color or []]
Definition at line 438 of file print_color.py.
help
print_color.help
Definition at line 362 of file print_color.py.
left_args
print_color.left_args
Definition at line 433 of file print_color.py.
metavar
print_color.metavar
Definition at line 371 of file print_color.py.
options
print_color.options
Definition at line 433 of file print_color.py.
parser
print_color.parser = OptionParser(usage)
Definition at line 355 of file print_color.py.
print_options
list print_color.print_options = []
Definition at line 436 of file print_color.py.
print_stream
str print_color.print_stream = "stdout"
Definition at line 435 of file print_color.py.
usage
str print_color.usage = "usage: %prog [options...] <format message> [format parameters...]"
Definition at line 354 of file print_color.py.