libcopp: task_action_functor< Ty > Class Template Reference
task_action_functor< Ty > Class Template Reference
#include <task_actions.h>
Public Types
using value_type = typename std::decay< Ty >::type
Public Member Functions
template<typename... TARG>
task_action_functor (TARG &&...arg)
template<typename... TARG>
task_action_functor (task_action_functor &&other, TARG &&...)
template<typename... TARG>
task_action_functor (const task_action_functor &other, TARG &&...)
~task_action_functor ()
int operator() (void *priv_data) override
virtual int on_finished (task_impl &)
Static Public Member Functions
static void placement_destroy (void *selfp)
Private Attributes
value_type functor_
Detailed Description
template<typename Ty>
class task_action_functor< Ty >
Definition at line 66 of file task_actions.h.
Member Typedef Documentation
value_type
template<typename Ty > using task_action_functor< Ty >::value_type = typename std::decay<Ty>::type
Definition at line 68 of file task_actions.h.
Constructor & Destructor Documentation
task_action_functor() [1/3]
template<typename Ty > template<typename... TARG> task_action_functor< Ty >::task_action_functor (TARG &&... arg) inline
Definition at line 71 of file task_actions.h.
task_action_functor() [2/3]
template<typename Ty > template<typename... TARG> task_action_functor< Ty >::task_action_functor (task_action_functor< Ty > && other, TARG && ...) inline
Definition at line 74 of file task_actions.h.
task_action_functor() [3/3]
template<typename Ty > template<typename... TARG> task_action_functor< Ty >::task_action_functor (const task_action_functor< Ty > & other, TARG && ...) inline
Definition at line 77 of file task_actions.h.
~task_action_functor()
template<typename Ty > task_action_functor< Ty >::~task_action_functor () inline
Definition at line 79 of file task_actions.h.
Referenced by task_action_functor< Ty >::placement_destroy().
Member Function Documentation
on_finished()
LIBCOPP_COTASK_API int impl::task_action_impl::on_finished (task_impl &) virtual inherited
Definition at line 19 of file task_action_impl.cpp.
Referenced by impl::task_impl::_notify_finished().
operator()()
template<typename Ty > int task_action_functor< Ty >::operator() (void * priv_data) inline override virtual
Implements impl::task_action_impl.
Definition at line 80 of file task_actions.h.
References detail::task_action_functor_check::call().
placement_destroy()
template<typename Ty > static void task_action_functor< Ty >::placement_destroy (void * selfp) inline static
Definition at line 84 of file task_actions.h.
References task_action_functor< Ty >::~task_action_functor().
Field Documentation
functor_
template<typename Ty > value_type task_action_functor< Ty >::functor_ private
Definition at line 94 of file task_actions.h.
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcotask/task_actions.h