libcopp: /home/runner/work/libcopp/libcopp/sample/sample_readme_2.cpp File Reference
sample_readme_2.cpp File Reference
#include <iostream>
#include <libcotask/task.h>
Typedefs
typedef cotask::task my_task_t
Functions
int main ()
Typedef Documentation
my_task_t
typedef cotask::task my_task_t
Definition at line 6 of file sample_readme_2.cpp.
Function Documentation
main()
int main ()
Definition at line 8 of file sample_readme_2.cpp.
References impl::task_impl::get_id(), this_task::get_task(), task< TCO_MACRO >::resume(), task< TCO_MACRO >::start(), and impl::task_impl::yield().