libcopp: memory::intrusive_ptr< T > Class Template Reference
memory::intrusive_ptr< T > Class Template Reference
#include <intrusive_ptr.h>
Public Types
using self_type = intrusive_ptr< T >
using element_type = T
Public Member Functions
constexpr intrusive_ptr () noexcept
intrusive_ptr (T *p, bool add_ref=true)
template<typename U >
intrusive_ptr (intrusive_ptr< U > const &rhs, typename std::enable_if< std::is_convertible< U *, T * >::value >::type *=nullptr)
intrusive_ptr (self_type const &rhs)
~intrusive_ptr ()
template<typename U >
intrusive_ptr & operator= (intrusive_ptr< U > const &rhs)
intrusive_ptr (self_type &&rhs) noexcept
self_type & operator= (self_type &&rhs) noexcept
template<typename U >
intrusive_ptr (intrusive_ptr< U > &&rhs, typename std::enable_if< std::is_convertible< U *, T * >::value >::type *=nullptr) noexcept
template<typename U , typename Deleter >
self_type & operator= (std::unique_ptr< U, Deleter > &&rhs)
self_type & operator= (self_type const &rhs)
void reset () noexcept
void reset (element_type *rhs)
void reset (element_type *rhs, bool add_ref)
element_type * get () const noexcept
element_type * detach () noexcept
element_type & operator* () const
element_type * operator-> () const
operator bool () const noexcept
bool operator! () const noexcept
void swap (intrusive_ptr &rhs) noexcept
Private Attributes
element_type * px
Friends
template<typename U >
class intrusive_ptr
Detailed Description
template<typename T>
class memory::intrusive_ptr< T >
Definition at line 42 of file intrusive_ptr.h.
Member Typedef Documentation
element_type
template<typename T > using memory::intrusive_ptr< T >::element_type = T
Definition at line 45 of file intrusive_ptr.h.
self_type
template<typename T > using memory::intrusive_ptr< T >::self_type = intrusive_ptr<T>
Definition at line 44 of file intrusive_ptr.h.
Constructor & Destructor Documentation
intrusive_ptr() [1/6]
template<typename T > constexpr memory::intrusive_ptr< T >::intrusive_ptr () inline constexpr noexcept
Definition at line 47 of file intrusive_ptr.h.
intrusive_ptr() [2/6]
template<typename T > memory::intrusive_ptr< T >::intrusive_ptr (T * p, bool add_ref = true) inline
Definition at line 49 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
intrusive_ptr() [3/6]
template<typename T > template<typename U > memory::intrusive_ptr< T >::intrusive_ptr (intrusive_ptr< U > const & rhs, typename std::enable_if< std::is_convertible< U *, T * >::value >::type * = nullptr) inline
Definition at line 56 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
intrusive_ptr() [4/6]
template<typename T > memory::intrusive_ptr< T >::intrusive_ptr (self_type const & rhs) inline
Definition at line 64 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
~intrusive_ptr()
template<typename T > memory::intrusive_ptr< T >::~intrusive_ptr () inline
Definition at line 70 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
intrusive_ptr() [5/6]
template<typename T > memory::intrusive_ptr< T >::intrusive_ptr (self_type && rhs) inline noexcept
Definition at line 86 of file intrusive_ptr.h.
intrusive_ptr() [6/6]
template<typename T > template<typename U > memory::intrusive_ptr< T >::intrusive_ptr (intrusive_ptr< U > && rhs, typename std::enable_if< std::is_convertible< U *, T * >::value >::type * = nullptr) inline noexcept
Definition at line 94 of file intrusive_ptr.h.
Member Function Documentation
detach()
template<typename T > element_type * memory::intrusive_ptr< T >::detach () inline noexcept
Definition at line 119 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
get()
template<typename T > element_type * memory::intrusive_ptr< T >::get () const inline noexcept
Definition at line 117 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
Referenced by memory::const_pointer_cast(), memory::get_pointer(), and memory::static_pointer_cast().
operator bool()
template<typename T > memory::intrusive_ptr< T >::operator bool () const inline noexcept
Definition at line 136 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
operator!()
template<typename T > bool memory::intrusive_ptr< T >::operator! () const inline noexcept
Definition at line 138 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
operator*()
template<typename T > element_type & memory::intrusive_ptr< T >::operator* () const inline
Definition at line 125 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
operator->()
template<typename T > element_type * memory::intrusive_ptr< T >::operator-> () const inline
Definition at line 130 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
operator=() [1/4]
template<typename T > template<typename U > intrusive_ptr & memory::intrusive_ptr< T >::operator= (intrusive_ptr< U > const & rhs) inline
Definition at line 80 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::swap().
operator=() [2/4]
template<typename T > self_type & memory::intrusive_ptr< T >::operator= (self_type && rhs) inline noexcept
Definition at line 88 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::swap().
operator=() [3/4]
template<typename T > self_type & memory::intrusive_ptr< T >::operator= (self_type const & rhs) inline
Definition at line 106 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::swap().
operator=() [4/4]
template<typename T > template<typename U , typename Deleter > self_type & memory::intrusive_ptr< T >::operator= (std::unique_ptr< U, Deleter > && rhs) inline
Definition at line 101 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::swap().
reset() [1/3]
template<typename T > void memory::intrusive_ptr< T >::reset () inline noexcept
Definition at line 111 of file intrusive_ptr.h.
reset() [2/3]
template<typename T > void memory::intrusive_ptr< T >::reset (element_type * rhs) inline
Definition at line 113 of file intrusive_ptr.h.
reset() [3/3]
template<typename T > void memory::intrusive_ptr< T >::reset (element_type * rhs, bool add_ref) inline
Definition at line 115 of file intrusive_ptr.h.
swap()
template<typename T > void memory::intrusive_ptr< T >::swap (intrusive_ptr< T > & rhs) inline noexcept
Definition at line 140 of file intrusive_ptr.h.
References memory::intrusive_ptr< T >::px.
Referenced by memory::intrusive_ptr< T >::operator=(), memory::intrusive_ptr< T >::operator=(), memory::intrusive_ptr< T >::operator=(), memory::intrusive_ptr< T >::operator=(), and memory::swap().
Friends And Related Symbol Documentation
intrusive_ptr
template<typename T > template<typename U > friend class intrusive_ptr friend
Definition at line 77 of file intrusive_ptr.h.
Field Documentation
px
template<typename T > element_type* memory::intrusive_ptr< T >::px private
Definition at line 147 of file intrusive_ptr.h.
Referenced by memory::intrusive_ptr< T >::detach(), memory::intrusive_ptr< T >::get(), memory::intrusive_ptr< T >::intrusive_ptr(), memory::intrusive_ptr< T >::intrusive_ptr(), memory::intrusive_ptr< T >::intrusive_ptr(), memory::intrusive_ptr< T >::operator bool(), memory::intrusive_ptr< T >::operator!(), memory::intrusive_ptr< T >::operator*(), memory::intrusive_ptr< T >::operator->(), memory::intrusive_ptr< T >::swap(), and memory::intrusive_ptr< T >::~intrusive_ptr().
The documentation for this class was generated from the following file:
/home/runner/work/libcopp/libcopp/include/libcopp/utils/memory/intrusive_ptr.h