libcopp: libcopp_internal_api_set Struct Reference
libcopp_internal_api_set Struct Reference
Public Types
using jump_src_data_t = coroutine_context::jump_src_data_t
Static Public Member Functions
static LIBCOPP_UTIL_FORCEINLINE void set_caller (coroutine_context *src, const fcontext::fcontext_t &fctx)
static LIBCOPP_UTIL_FORCEINLINE void set_callee (coroutine_context *src, const fcontext::fcontext_t &fctx)
static void coroutine_context_callback (LIBCOPP_COPP_NAMESPACE_ID::fcontext::transfer_t src_ctx)
Detailed Description
Definition at line 132 of file coroutine_context.cpp.
Member Typedef Documentation
jump_src_data_t
using libcopp_internal_api_set::jump_src_data_t = coroutine_context::jump_src_data_t
Definition at line 133 of file coroutine_context.cpp.
Member Function Documentation
coroutine_context_callback()
static void libcopp_internal_api_set::coroutine_context_callback (LIBCOPP_COPP_NAMESPACE_ID::fcontext::transfer_t src_ctx) inline static
Definition at line 164 of file coroutine_context.cpp.
References coroutine_context::callee_, coroutine_context::caller_, coroutine_context_base::flag_type::EN_CFT_FINISHED, coroutine_context::flags_, coroutine_context::jump_src_data_t::from_co, coroutine_context::jump_src_data_t::priv_data, coroutine_context_base::run_and_recv_retcode(), detail::set_this_coroutine_context(), coroutine_context::jump_src_data_t::to_co, and coroutine_context::yield().
Referenced by coroutine_context::create().
set_callee()
static LIBCOPP_UTIL_FORCEINLINE void libcopp_internal_api_set::set_callee (coroutine_context * src, const fcontext::fcontext_t & fctx) inline static
Definition at line 141 of file coroutine_context.cpp.
References coroutine_context::callee_.
Referenced by jump_to().
set_caller()
static LIBCOPP_UTIL_FORCEINLINE void libcopp_internal_api_set::set_caller (coroutine_context * src, const fcontext::fcontext_t & fctx) inline static
Definition at line 135 of file coroutine_context.cpp.
References coroutine_context::caller_.
Referenced by jump_to().
The documentation for this struct was generated from the following file:
/home/runner/work/libcopp/libcopp/src/libcopp/coroutine/coroutine_context.cpp