libcopp: detail Namespace Reference
detail Namespace Reference
Data Structures
struct task_action_functor_check
struct tickspec_t
struct task_timer_node
struct task_manager_node< task< TCO_MACRO > >
struct test_manager_tls_block_t
struct topological_sort_object_t
Functions
static void init_pthread_this_coroutine_context ()
static void set_this_coroutine_context (coroutine_context_base *p)
static coroutine_context_base * get_this_coroutine_context ()
static std::size_t pagesize ()
static rlimit stacksize_limit_ ()
static rlimit stacksize_limit ()
static void system_info_ (SYSTEM_INFO *si)
static SYSTEM_INFO system_info ()
static std::size_t pagesize ()
test_manager_tls_block_t * get_test_manager_tls_block ()
Variables
template<class TTask >
struct LIBCOPP_COTASK_API_HEAD_ONLY task_manager_node
static pthread_once_t gt_coroutine_init_once = PTHREAD_ONCE_INIT
static pthread_key_t gt_coroutine_tls_key
static test_manager_tls_block_t g_global_counter_cache = {0, 0}
Function Documentation
get_test_manager_tls_block()
test_manager_tls_block_t* detail::get_test_manager_tls_block ()
Definition at line 43 of file test_manager.cpp.
References g_global_counter_cache.
Referenced by test_manager::inc_failed_counter(), test_manager::inc_success_counter(), and test_manager::set_counter_ptr().
get_this_coroutine_context()
static coroutine_context_base* detail::get_this_coroutine_context () inline static
Definition at line 60 of file coroutine_context.cpp.
References gt_coroutine_init_once, gt_coroutine_tls_key, and init_pthread_this_coroutine_context().
Referenced by this_coroutine::get_coroutine(), coroutine_context_base::get_this_coroutine_base(), coroutine_context::start(), and this_coroutine::yield().
init_pthread_this_coroutine_context()
static void detail::init_pthread_this_coroutine_context () static
Definition at line 48 of file coroutine_context.cpp.
References gt_coroutine_tls_key.
Referenced by get_this_coroutine_context(), and set_this_coroutine_context().
pagesize() [1/2]
static std::size_t detail::pagesize () static
Definition at line 41 of file stack_traits_posix.cpp.
References gsl::size().
Referenced by stack_traits::page_size(), and stack_traits::round_to_page_size().
pagesize() [2/2]
static std::size_t detail::pagesize () static
Definition at line 85 of file stack_traits_windows.cpp.
References system_info().
set_this_coroutine_context()
static void detail::set_this_coroutine_context (coroutine_context_base * p) inline static
Definition at line 51 of file coroutine_context.cpp.
References gt_coroutine_init_once, gt_coroutine_tls_key, and init_pthread_this_coroutine_context().
Referenced by libcopp_internal_api_set::coroutine_context_callback(), jump_to(), and coroutine_context_base::set_this_coroutine_base().
stacksize_limit()
static rlimit detail::stacksize_limit () static
Definition at line 53 of file stack_traits_posix.cpp.
References stacksize_limit_().
Referenced by stack_traits::is_unbounded(), and stack_traits::maximum_size().
stacksize_limit_()
static rlimit detail::stacksize_limit_ () static
Definition at line 46 of file stack_traits_posix.cpp.
Referenced by stacksize_limit().
system_info()
static SYSTEM_INFO detail::system_info () static
Definition at line 63 of file stack_traits_windows.cpp.
References system_info_().
Referenced by pagesize().
system_info_()
static void detail::system_info_ (SYSTEM_INFO * si) static
Definition at line 61 of file stack_traits_windows.cpp.
Referenced by system_info().
Variable Documentation
g_global_counter_cache
test_manager_tls_block_t detail::g_global_counter_cache = {0, 0} static
Definition at line 42 of file test_manager.cpp.
Referenced by get_test_manager_tls_block(), and test_manager::set_counter_ptr().
gt_coroutine_init_once
pthread_once_t detail::gt_coroutine_init_once = PTHREAD_ONCE_INIT static
Definition at line 46 of file coroutine_context.cpp.
Referenced by get_this_coroutine_context(), and set_this_coroutine_context().
gt_coroutine_tls_key
pthread_key_t detail::gt_coroutine_tls_key static
Definition at line 47 of file coroutine_context.cpp.
Referenced by get_this_coroutine_context(), init_pthread_this_coroutine_context(), and set_this_coroutine_context().
task_manager_node
template<class TTask > struct LIBCOPP_COTASK_API_HEAD_ONLY detail::task_manager_node
Definition at line 1467 of file task_manager.h.