libcopp: shared_from_this Namespace Reference
shared_from_this Namespace Reference
Data Structures
class impl
class impl2
struct V
class X
class Y
Functions
copp::memory::strong_rc_ptr< Y > createY ()
void test ()
void test2 ()
void test3 ()
CASE_TEST (rc_ptr, shared_from_this)
Function Documentation
CASE_TEST()
shared_from_this::CASE_TEST (rc_ptr , shared_from_this) private
Definition at line 4242 of file rc_ptr_test.cpp.
References test(), test2(), and test3().
createY()
copp::memory::strong_rc_ptr< Y > shared_from_this::createY () private
Definition at line 4266 of file rc_ptr_test.cpp.
Referenced by test().
test()
void shared_from_this::test () private
Definition at line 4214 of file rc_ptr_test.cpp.
References CASE_EXPECT_ERROR, CASE_EXPECT_TRUE, and createY().
Referenced by CASE_TEST().
test2()
void shared_from_this::test2 () private
Definition at line 4271 of file rc_ptr_test.cpp.
Referenced by CASE_TEST().
test3()
void shared_from_this::test3 () private
Definition at line 4277 of file rc_ptr_test.cpp.
References CASE_EXPECT_ERROR, and CASE_EXPECT_TRUE.
Referenced by CASE_TEST().