libcopp: /home/runner/work/libcopp/libcopp/test/case/future_test.cpp File Reference
future_test.cpp File Reference
#include <libcopp/future/future.h>
#include <libcopp/future/poller.h>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <string>
#include "frame/test_macros.h"
Data Structures
struct test_no_trivial_parent_clazz
struct test_no_trivial_child_clazz
struct test_trivial_clazz
Functions
CASE_TEST (future, poll_void)
CASE_TEST (future, poll_trival)
CASE_TEST (future, poll_trival_object)
CASE_TEST (future, poll_no_trivial)
CASE_TEST (future, poll_shared_ptr)
CASE_TEST (future, poll_void_reset_and_swap)
CASE_TEST (future, poll_trivial_reset_and_swap)
CASE_TEST (future, poll_no_trivial_reset_and_swap)
CASE_TEST (future, swap_trivial_result)
CASE_TEST (future, swap_no_trivial_result)
CASE_TEST (future, future_with_void_result)
CASE_TEST (future, future_with_trival_result)
CASE_TEST (future, future_with_no_trival_result)
CASE_TEST (future, future_with_copp_trivial_result)
CASE_TEST (future, future_with_copp_no_trivial_result)
Function Documentation
CASE_TEST() [1/15]
CASE_TEST (future , future_with_copp_no_trivial_result)
Definition at line 307 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and COPP_IS_TIRVIALLY_COPYABLE_V.
CASE_TEST() [2/15]
CASE_TEST (future , future_with_copp_trivial_result)
Definition at line 289 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and COPP_IS_TIRVIALLY_COPYABLE_V.
CASE_TEST() [3/15]
CASE_TEST (future , future_with_no_trival_result)
Definition at line 274 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [4/15]
CASE_TEST (future , future_with_trival_result)
Definition at line 258 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [5/15]
CASE_TEST (future , future_with_void_result)
Definition at line 245 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [6/15]
CASE_TEST (future , poll_no_trivial)
Definition at line 101 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [7/15]
CASE_TEST (future , poll_no_trivial_reset_and_swap)
Definition at line 184 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and util::swap().
CASE_TEST() [8/15]
CASE_TEST (future , poll_shared_ptr)
Definition at line 115 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [9/15]
CASE_TEST (future , poll_trival)
Definition at line 65 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [10/15]
CASE_TEST (future , poll_trival_object)
Definition at line 87 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [11/15]
CASE_TEST (future , poll_trivial_reset_and_swap)
Definition at line 163 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and util::swap().
CASE_TEST() [12/15]
CASE_TEST (future , poll_void)
Definition at line 45 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, and CASE_EXPECT_TRUE.
CASE_TEST() [13/15]
CASE_TEST (future , poll_void_reset_and_swap)
Definition at line 143 of file future_test.cpp.
References CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and util::swap().
CASE_TEST() [14/15]
CASE_TEST (future , swap_no_trivial_result)
Definition at line 226 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and util::swap().
CASE_TEST() [15/15]
CASE_TEST (future , swap_trivial_result)
Definition at line 205 of file future_test.cpp.
References CASE_EXPECT_EQ, CASE_EXPECT_FALSE, CASE_EXPECT_TRUE, and util::swap().